### ISSUE TITLE
Facebook channel issue on core 0.11.6 , 0.11.7 and 0.11.8

### ISSUE THREAD

**Issue by amsolu** [RasaHQ/rasa_core#1125]
**Rasa Core version**: now -> 0.11.5 (have the issue on newer versions

**Python version**: 3.6

Linux UBUNTU 18 

Hi, I was working in a bot with Telegram with no issues for a while. Then I decided to give a try to facebook channel.

I was having the issue for hours : fb secret is not match and a 500 error from facebook. After checking, re-checking and changing Apps in facebooks, to the point I was like 99.99% everything was correct.

I tried to change rasa_core version starting on v-0.11.5 and everything starts to work perfectly. I was able to chat in messenger

then I tried 0.11.6 get the error 0.11.7 error and 0.11.8 error went back to 0.11.5 and everything starts to work again perfect.

Not sure where but looks like something change in versions 0.11.6 and up with the facebook channel. Could you please advise if there is any new config we need to change or there is something in the code sending the wrong secret to fb?

Thanks

**Comment by akelad** [comment]
Can you post the exact error trace you're getting please?

**Comment by amsolu** [comment]
This is the error we are receiving when we are going beyond version 0.11.5

127.0.0.1 - - [2018-10-05 07:25:16] "POST /webhooks/facebook/webhook HTTP/1.1" 500 444 0.003770
2018-10-05 07:25:20 ERROR    flask.app  - Exception on /webhooks/facebook/webhook [POST]
Traceback (most recent call last):
  File "/home/python/anaconda3/envs/bot36/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/python/anaconda3/envs/bot36/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/python/anaconda3/envs/bot36/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/python/anaconda3/envs/bot36/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python/anaconda3/envs/bot36/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/python/anaconda3/envs/bot36/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/python/anaconda3/envs/bot36/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/python/anaconda3/envs/bot36/lib/python3.6/site-packages/rasa_core/channels/facebook.py", line 273, in webhook
    messenger.handle(request.get_json(force=True))
  File "/home/python/anaconda3/envs/bot36/lib/python3.6/site-packages/fbmessenger/__init__.py", line 259, in handle
    return self.message(message)
  File "/home/python/anaconda3/envs/bot36/lib/python3.6/site-packages/rasa_core/channels/facebook.py", line 62, in message
    self._handle_user_message(text, self.get_user_id())
  File "/home/python/anaconda3/envs/bot36/lib/python3.6/site-packages/rasa_core/channels/facebook.py", line 77, in _handle_user_message
    input_channel=self.name())
AttributeError: 'Messenger' object has no attribute 'name'
127.0.0.1 - - [2018-10-05 07:25:20] "POST /webhooks/facebook/webhook HTTP/1.1" 500 444 0.004028


I am pretty sure is the same one 1118, 1107, are having I also have seen someone else with the same issue in the weather bot from Justina who fixed downgrading to 0.11.5

This error is for 0.11.9 but is consistency from 0.11.6

**Comment by amsolu** [comment]
I corrected the code now

**Comment by akelad** [comment]
awesome thanks

**Comment by amsolu** [comment]
Thank you very much!!!
We manually change the facebook.py and is working perfectly :)

**Comment by akelad** [comment]
in future we'd also welcome a pull request if you've fixed it yourself already ;) also 0.11.11 is available now

**Comment by amsolu** [comment]
Oh, don't misunderstand me Akelad,
I just review what you discovered and applied while you have been working on the internal process to get everything well done, we didn't fix anything just check the fix.
Sorry if I confused.
Have a great weekend

**Comment by akelad** [comment]
haha yeah i just meant that if you've found the fix for something we'd also just happily accept a PR for the fix :)
