### ISSUE TITLE
HTTP train

### ISSUE THREAD

**Issue by cisnky** [RasaHQ/rasa_core#1131]
**Rasa Core version**: 

**Python version**: 3.6

**Operating system** (windows, osx, ...): OSX

**Issue**: Rasa NLU: 0.13.4

I'm trying to train my model using the HTTP train endpoint.

If I use the model found in rasa_nlu/data/examples/rasa/demo-rasa.md with

`curl -XPOST -H "Content-Type: application/x-yml" localhost:5005/train?project=via_http -d @http_train.md`

I get the following response.

`{
  "error": "'NoneType' object has no attribute 'get'"
}`

What am I doing wrong?

**Content of domain file** (if used & relevant):
```yaml

## intent:affirm
- yes
- yep
- yeah
- indeed
- that's right
- ok
- great
- right, thank you
- correct
- great choice
- sounds really good

## intent:goodbye
- bye
- goodbye
- good bye
- stop
- end
- farewell
- Bye bye
- have a good one

## intent:greet
- hey
- howdy
- hey there
- hello
- hi
- good morning
- good evening
- dear sir

## intent:restaurant_search
- i'm looking for a place to eat
- I want to grab lunch
- I am searching for a dinner spot
- i'm looking for a place in the [north](location) of town
- show me [chinese](cuisine) restaurants
- show me [chines](cuisine:chinese) restaurants in the [north](location)
- show me a [mexican](cuisine) place in the [centre](location)
- i am looking for an [indian](cuisine) spot called olaolaolaolaolaola
- search for restaurants
- anywhere in the [west](location)
- anywhere near [18328](location)
- I am looking for [asian fusion](cuisine) food
- I am looking a restaurant in [29432](location)
- I am looking for [mexican indian fusion](cuisine)
- [central](location) [indian](cuisine) restaurant

## synonym:chinese
+ Chines
* Chinese

## synonym:vegetarian
- vegg
- veggie

## regex:zipcode
- [0-9]{5}

## regex:greet
- hey[^\s]*
```

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hey @cisnky!  Do you get a traceback with this response?  If so, please post it here and it will help me diagnose the problem

**Comment by cisnky** [comment]
Thanks, @akelad & @MetcalfeTom for getting back to me.

Here's the trace

> 2018-10-04 16:36:10+0100 [-] "127.0.0.1" - - [04/Oct/2018:15:36:10 +0000] "POST /train?project=via_http HTTP/1.1" 500 60 "-" "curl/7.54.0"
^[[A2018-10-04 16:42:11+0100 [-] "127.0.0.1" - - [04/Oct/2018:15:42:11 +0000] "POST /train HTTP/1.1" 404 46 "-" "curl/7.54.0"
^[[A^[[D2018-10-04 16:43:46+0100 [-] 2018-10-04 16:43:46 ERROR    rasa_nlu.train  - Failed to train project 'current'.
2018-10-04 16:43:46+0100 [-] Traceback (most recent call last):
2018-10-04 16:43:46+0100 [-]   File "/Users/anthonyo/development/rasa/env/lib/python3.6/site-packages/rasa_nlu/train.py", line 125, in do_train_in_worker
2018-10-04 16:43:46+0100 [-]     component_builder)
2018-10-04 16:43:46+0100 [-]   File "/Users/anthonyo/development/rasa/env/lib/python3.6/site-packages/rasa_nlu/train.py", line 153, in do_train
2018-10-04 16:43:46+0100 [-]     training_data = load_data(data, cfg.language)
2018-10-04 16:43:46+0100 [-]   File "/Users/anthonyo/development/rasa/env/lib/python3.6/site-packages/rasa_nlu/training_data/loading.py", line 55, in load_data
2018-10-04 16:43:46+0100 [-]     data_sets = [_load(f, language) for f in files]
2018-10-04 16:43:46+0100 [-]   File "/Users/anthonyo/development/rasa/env/lib/python3.6/site-packages/rasa_nlu/training_data/loading.py", line 55, in <listcomp>
2018-10-04 16:43:46+0100 [-]     data_sets = [_load(f, language) for f in files]
2018-10-04 16:43:46+0100 [-]   File "/Users/anthonyo/development/rasa/env/lib/python3.6/site-packages/rasa_nlu/training_data/loading.py", line 101, in _load
2018-10-04 16:43:46+0100 [-]     fformat = _guess_format(filename)
2018-10-04 16:43:46+0100 [-]   File "/Users/anthonyo/development/rasa/env/lib/python3.6/site-packages/rasa_nlu/training_data/loading.py", line 126, in _guess_format
2018-10-04 16:43:46+0100 [-]     if format_heuristic(js, filename):
2018-10-04 16:43:46+0100 [-]   File "/Users/anthonyo/development/rasa/env/lib/python3.6/site-packages/rasa_nlu/training_data/loading.py", line 36, in <lambda>
2018-10-04 16:43:46+0100 [-]     WIT: lambda js, fn: "data" in js and isinstance(js.get("data"), list),
2018-10-04 16:43:46+0100 [-] TypeError: argument of type 'NoneType' is not iterable
2018-10-04 16:43:46+0100 [-] 2018-10-04 16:43:46 WARNING  rasa_nlu.data_router  - [Failure instance: Traceback (failure with no frames): <class 'rasa_nlu.train.TrainingException'>: argument of type 'NoneType' is not iterable

**Comment by MetcalfeTom** [comment]
Hmm, it seems to me that the `json.loads(content)` line in our `_guess_format()` is returning a `None` value instead of raising a `ValueError`

Just to be sure, could you training again, using the `demo-rasa.json` training data?

**Comment by cisnky** [comment]
@meandor with the json example

> 2018-10-05 12:32:56+0100 [-] 2018-10-05 12:32:56 ERROR    rasa_nlu.train  - Failed to train project 'via_http'.
2018-10-05 12:32:56+0100 [-] Traceback (most recent call last):
2018-10-05 12:32:56+0100 [-]   File "/Users/anthonyo/development/rasa/env/lib/python3.6/site-packages/rasa_nlu/train.py", line 125, in do_train_in_worker
2018-10-05 12:32:56+0100 [-]     component_builder)
2018-10-05 12:32:56+0100 [-]   File "/Users/anthonyo/development/rasa/env/lib/python3.6/site-packages/rasa_nlu/train.py", line 153, in do_train
2018-10-05 12:32:56+0100 [-]     training_data = load_data(data, cfg.language)
2018-10-05 12:32:56+0100 [-]   File "/Users/anthonyo/development/rasa/env/lib/python3.6/site-packages/rasa_nlu/training_data/loading.py", line 55, in load_data
2018-10-05 12:32:56+0100 [-]     data_sets = [_load(f, language) for f in files]
2018-10-05 12:32:56+0100 [-]   File "/Users/anthonyo/development/rasa/env/lib/python3.6/site-packages/rasa_nlu/training_data/loading.py", line 55, in <listcomp>
2018-10-05 12:32:56+0100 [-]     data_sets = [_load(f, language) for f in files]
2018-10-05 12:32:56+0100 [-]   File "/Users/anthonyo/development/rasa/env/lib/python3.6/site-packages/rasa_nlu/training_data/loading.py", line 101, in _load
2018-10-05 12:32:56+0100 [-]     fformat = _guess_format(filename)
2018-10-05 12:32:56+0100 [-]   File "/Users/anthonyo/development/rasa/env/lib/python3.6/site-packages/rasa_nlu/training_data/loading.py", line 126, in _guess_format
2018-10-05 12:32:56+0100 [-]     if format_heuristic(js, filename):
2018-10-05 12:32:56+0100 [-]   File "/Users/anthonyo/development/rasa/env/lib/python3.6/site-packages/rasa_nlu/training_data/loading.py", line 36, in <lambda>
2018-10-05 12:32:56+0100 [-]     WIT: lambda js, fn: "data" in js and isinstance(js.get("data"), list),
2018-10-05 12:32:56+0100 [-] TypeError: argument of type 'NoneType' is not iterable
2018-10-05 12:32:56+0100 [-] 2018-10-05 12:32:56 WARNING  rasa_nlu.data_router  - [Failure instance: Traceback (failure with no frames): <class 'rasa_nlu.train.TrainingException'>: argument of type 'NoneType' is not iterable

**Comment by MetcalfeTom** [comment]
Ahh OK I think I know what's going on here.

Like it's [mentioned in the docs](https://rasa.com/docs/nlu/http/#post-train), your request header declares the content-type as a YAML file, but the training data is being sent in markdown/JSON.

Hopefully one of these two options solves your issue now:  Either rename `http_train.md` to `http_train.yml` or try the following command with your JSON file:

`curl -XPOST -H"Content-Type: application/json" localhost:5005/train?project=via_http -d @http_train.json`

Let me know if this fixes your issue!

**Comment by cisnky** [comment]
@MetcalfeTom 

Many thanks for continuing to look into the issue.

It works when I try JSON but I get the following error when using yml.

I tried 

`curl -XPOST -H "Content-Type: application/json" localhost:5005/train?project=via_http -d @http_train.json`

and got the following

`{
  "error": "'NoneType' object has no attribute 'get'"
}`

Nothing else in the logs.

Model

`## intent:greet
- hey
- hello
- hi
- good morning
- good evening
- hey there`

**Comment by MetcalfeTom** [comment]
No problem!  Try re-formatting the file like this:

```
language: "en"

pipeline: "spacy_sklearn"

data: |
  ## intent:affirm
  - yes
  - yep
  - yeah
  ...
```

i.e. with `data: |` in front of the training data, and with all subsequent parts indented by two whitespace.

**Comment by cisnky** [comment]
@MetcalfeTom 

Thanks for all your help. Now working, changed the curl request with the re-formatted the YAML.

`curl -XPOST -H "Content-Type: application/x-yml" localhost:5005/train?project=via_http --data-binary @http_train.yml`

**Comment by MetcalfeTom** [comment]
Awesome!  Glad to help
