### ISSUE TITLE
Issue with creating an agent - using custom channel to create a widget

### ISSUE THREAD

**Issue by vishnudatsci** [RasaHQ/rasa_core#1234]
**Rasa Core version**: rasa-core           0.10.4
                                    rasa-nlu            0.13.1

**Python version**: 3.6.1

**Operating system**  Windows 10

**Issue**:

 I am trying to add the https://github.com/JustinaPetr/Weatherbot_Tutorial 'WEATHER BOT' to a website. (Or sample HTML) page. I used the steps given in Advanced Usage with a custom Rasa Core project as Custom Channel from Python using https://github.com/scalableminds/chatroom

Following is the code I ran ('run_application.py')

```
import os
from rasa_core.channels import HttpInputChannel
from rasa_core.agent import Agent
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_slack_connector import SlackInput
from bot_server_channel import BotServerInputChannel

# Creating the Interpreter and Agent
def load_agent(): 
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/productnlu')
    agent = Agent.load('./models/dialogue', interpreter = nlu_interpreter)

# Creating the server
def main_server():
    agent = load_agent()

    channel = BotServerInputChannel(agent, port=5005)
    agent.handle_channels([channel], http_port=5005)

main_server()
```
Got error **@ agent.handle_channels([channel], http_port=cmdline_args.port)**

```
Traceback (most recent call last):
  File "run_application.py", line 23, in <module>
    main_server()
  File "run_application.py", line 21, in main_server
    agent.handle_channels([channel], http_port=5005)
AttributeError: 'NoneType' object has no attribute 'handle_channels'
```

Before creating a custom channel using chatroom, I tried the bot using slack with the following code. For the current code, the only change is creating the server. I'm not sure what is wrong.

```

from rasa_core.channels import HttpInputChannel
from rasa_core.agent import Agent
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_slack_connector import SlackInput


nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/productnlu')
agent = Agent.load('./models/dialogue', interpreter = nlu_interpreter)

input_channel = SlackInput(
        #Access keys
        #Access Tokens,
        True)

agent.handle_channel(HttpInputChannel(5004, '/', input_channel))
```

**Comment by EPedrotti** [comment]
Hi @vishnudatsci, I think you are just missing a return statement at the end of the `load_agent` function.

**Comment by vishnudatsci** [comment]
I updated it to new RASA core version (Weatherbot Tutorial - using the latest release of Rasa NLU and Rasa Core) and tried to execute the custom channel code. I got the following error.
```

C:\Users\vishn\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
tf.estimator package not installed.
Traceback (most recent call last):
  File "run_application.py", line 2, in <module>
    from rasa_core.agent import Agent
  File "C:\Users\vishn\Anaconda3\lib\site-packages\rasa_core\agent.py", line 31, in <module>
    from rasa_core.policies import Policy
  File "C:\Users\vishn\Anaconda3\lib\site-packages\rasa_core\policies\__init__.py", line 9, in <module>
    from rasa_core.policies.keras_policy import KerasPolicy
  File "C:\Users\vishn\Anaconda3\lib\site-packages\rasa_core\policies\keras_policy.py", line 11, in <module>
    import tensorflow as tf
  File "C:\Users\vishn\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow import compat
  File "C:\Users\vishn\Anaconda3\lib\site-packages\tensorflow\compat\__init__.py", line 21, in <module>
    from tensorflow.python.compat.compat import forward_compatibility_horizon
ModuleNotFoundError: No module named 'tensorflow.python.compat'
```

**Comment by akelad** [comment]
@vishnudatsci did you install the associated requirements too? which tensorflow version do you have?
