### ISSUE TITLE
Fallback Policy is firing even when threshold is satisfied

### ISSUE THREAD

**Issue by diegodorgam** [RasaHQ/rasa_core#1255]
**Rasa Core version**: 0.11.12

**Python version**: 3.6

**Operating system** (windows, osx, ...):osx

**Issue**: Fallback Policy is not respecting nlu threshold, even when nlu intent is classified above the threshold, the Fallback Policy is activated and gives a utter_default response. 

Here are the logs

```
quem pode ser propoenente na lei
2018-10-31 20:23:41 DEBUG    rasa_core.tracker_store  - Recreating tracker for id 'default'
2018-10-31 20:23:41 DEBUG    rasa_core.processor  - Received user message 'quem pode ser proponente na lei' with intent '{'name': 'lei_rouanet_quem_pode_ser_proponente', 'confidence': 0.9024257659912109}' and entities '[]'
2018-10-31 20:23:41 DEBUG    rasa_core.processor  - Logged UserUtterance - tracker now has 22 events
2018-10-31 20:23:41 DEBUG    rasa_core.processor  - Current slot values:
	situacao_processo: None
2018-10-31 20:23:41 DEBUG    rasa_core.policies.memoization  - Current tracker state [{'prev_action_listen': 1.0, 'intent_lei_rouanet_quem_pode_ser_proponente': 1.0}, {'intent_lei_rouanet_quem_pode_ser_proponente': 1.0, 'prev_utter_default': 1.0}, {'prev_action_listen': 1.0, 'intent_lei_rouanet_quem_pode_ser_proponente': 1.0}]
2018-10-31 20:23:41 DEBUG    rasa_core.policies.memoization  - There is no memorised next action
2018-10-31 20:23:41 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_0_FallbackPolicy
2018-10-31 20:23:41 DEBUG    rasa_core.processor  - Predicted next action 'utter_default' with prob 1.00.
2018-10-31 20:23:41 DEBUG    rasa_core.processor  - Action 'utter_default' ended with events '[]'
2018-10-31 20:23:41 DEBUG    rasa_core.processor  - Bot utterance 'BotUttered(text: Desculpe, não consegui te entender
```

The training is done with this command:
```
python -m rasa_core.train -s bot/data/stories -d bot/domain.yml -o bot/models/dialogue --epochs 30 --augmentation 50 --history 3 --nlu_threshold 0.6 --core_threshold 0.6 --fallback_action_name 'utter_default'
```
Even with the intent classified with `0.90` confidence, and the threshold set to `0.6`, the FallbackPolicy is triggered to predict (?) next action.

I have followed instructions found in other issues, gave a fallback history like: 

```markdown
## fallback
  - utter_default
```
so the bot shouldn't loop over fallback. 
All stories have 3 intents length and gave the parameter `--history 3`.

still, not getting why fallback policy is even being triggered.

I've tested reducing the threshold parameters but still got the same behavior, any ideas why this could be happening?

_all code available in https://github.com/lappis-unb/tais/tree/2.1.0_

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by diegodorgam** [comment]
thanks @akelad

**Comment by MetcalfeTom** [comment]
Olá @diegodorgam,

You aren't passing a policy ensemble to train your bot.  We recently had support for a `policy_config.yml` written by a community member [so you could try testing it out here with a Memoization or Keras policy.](https://github.com/RasaHQ/rasa_core/pull/1169)

Let me know if this fixes/doesn't fix your problem.

**Comment by diegodorgam** [comment]
thanks @MetcalfeTom, but I still can't see why this method of loading the same parameters through a YAML file can give any different results. 
However, I tried to upgrade rasa-core using pip install --upgrade, but still got the same 0.11.8 version, which can't figure out the `-c` parameter. 
So I tried to install from master branch, got a 0.12.0a4 version which apparently has the -c argument parser, but gives me this error:
```
python -m rasa_core.train -s bot/data/stories -d bot/domain.yml -o bot/models/dialogue --epochs 30 --augmentation 50 --history 3 -c bot/policies.yml
Traceback (most recent call last):
  File "/anaconda3/envs/rouana/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/rouana/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/dorgam/www/lappis-unb/rasa_core/rasa_core/train.py", line 262, in <module>
    additional_arguments)
  File "/Users/dorgam/www/lappis-unb/rasa_core/rasa_core/train.py", line 176, in train_dialogue_model
    policies = config.load(policy_config, fallback_args, max_history)
  File "/Users/dorgam/www/lappis-unb/rasa_core/rasa_core/config.py", line 29, in load
    return PolicyEnsemble.from_dict(config_data)
  File "/Users/dorgam/www/lappis-unb/rasa_core/rasa_core/policies/ensemble.py", line 219, in from_dict
    policy_object = constr_func(**policy)
TypeError: __init__() got an unexpected keyword argument 'max_history'
make: *** [train-core] Error 1
```
It seems that train.py is not receiving the max_history parameter, although I'm passing it in the training command and inside policies.yml too:

```
policies:
  - name: "MemoizationPolicy"
    max_history: 3
  - name: "KerasPolicy"
    max_history: 3
  - name: "FallbackPolicy"
    nlu_threshold: 0.6
    core_threshold: 0.6
    fallback_action_name: "utter_default"
```

Is there something wrong that you can see in those steps that I took? 

Perhaps I should create a training python script to do this job, would that affect the Fallback Policy behavior somehow?

thks in advance

**Comment by diegodorgam** [comment]
Okay, so I've been trying some stuff here, first I've cloned FallbackPolicy class and created a new CustomFallbackPolicy class, with the following changes:
```python
def should_fallback(self,
                        nlu_confidence,  # type float
                        last_action_name  # type: Text
                        ):
        trigger = False
        if nlu_confidence < self.nlu_threshold:
            trigger = True
        if last_action_name == self.fallback_action_name:
            trigger = False
        if last_action_name is None:
            trigger = False

        return trigger

    def fallback_scores(self, domain, fallback_score=FALLBACK_SCORE):
        """Prediction scores used if a fallback is necessary."""
        result = [0.0] * domain.num_actions
        idx = domain.index_for_action(self.fallback_action_name)
        result[idx] = fallback_score
        return result

    def predict_action_probabilities(self, tracker, domain):
        # type: (DialogueStateTracker, Domain) -> List[float]
        """Predicts a fallback action if NLU confidence is low
            or no other policy has a high-confidence prediction"""

        nlu_data = tracker.latest_message.parse_data
        nlu_confidence = nlu_data["intent"].get("confidence", 0.0)
        if self.should_fallback(nlu_confidence, tracker.latest_action_name):
            logger.debug("NLU confidence {} is lower "
                         "than NLU threshold {}. "
                         "Predicting fallback action: {}"
                         "".format(nlu_confidence, self.nlu_threshold,
                                   self.fallback_action_name))
            # we set this to 1.1 to make sure fallback overrides
            # the memoization policy
            result = self.fallback_scores(domain)
        else:
            result = [0.0] * domain.num_actions

        return result
```

Not sure why core_threshold is set there, it seems that it isn't possible to have this value (I assume it suppose to be KerasPolicy result) from inside the tracker, once the tracker will only log one confidence score, which I assume it is the NLU confidence, so I've made a few tests with it and discovered that once the FallbackPolicy is triggered, the `last_message` within the tracker was holding some kind of `None` value for last_action_name, with confidence 0.0. 

So what I did there was to remove the `if tracker.latest_action_name == self.fallback_action_name:` block which was going to search for action_listen index to return with a big score, and gave a more simpler structure, just asking for `should_fallback` method to return a boolean, and if it returned `False`, give a bunch of zeros to the return.

Not really sure if what I did there should work in other cases, but it worked for me swell. 

Now the `CustomFallbackPolicy` returns the `utter_default` and `action_listen` at the first time if NLU confidence is lower than threshold, otherwise it is not triggered because it returns a bunch os zeros.

**Comment by MetcalfeTom** [comment]
Hey @diegodorgam 

Thanks for informing me of all of this.  The NLU confidence _is_ used to prevent Fallback from triggering, but, like you were discovering, your problem arises because your policies are not predicting the next action with a confidence above the `core_threshold`.  If it is always returning as `0.0` then I think there is an issue with the `max_history` parameter.

I'm still looking through your code, but was your bot working as intended before?  Or has this always been an issue since you started testing it?

**Comment by diegodorgam** [comment]
Hi there @akelad and @MetcalfeTom 

I think I've finally got this working with these methods:
```python
    def should_fallback(self,
                        nlu_confidence,  # type float
                        last_action_name  # type: Text
                        ):
        # type: (...) -> bool
        """It should predict fallback action only if
        a. predicted NLU confidence is lower than ``nlu_threshold`` &&
        b. last action is NOT fallback action
        """
        trigger = False
        if nlu_confidence < self.nlu_threshold:
            trigger = True
        if last_action_name == self.fallback_action_name:
            trigger = False
        if last_action_name is None:
            trigger = False

        return trigger

    def predict_action_probabilities(self, tracker, domain):
        # type: (DialogueStateTracker, Domain) -> List[float]
        """Predicts a fallback action if NLU confidence is low
            or no other policy has a high-confidence prediction"""

        nlu_data = tracker.latest_message.parse_data
        # if NLU interpreter does not provide confidence score,
        # it is set to 1.0 here in order
        # to not override standard behaviour
        nlu_confidence = nlu_data["intent"].get("confidence", 1.0)

        if self.should_fallback(nlu_confidence, tracker.latest_action_name):
            logger.debug("NLU confidence {} is lower "
                         "than NLU threshold {}. "
                         "Predicting fallback action: {}"
                         "".format(nlu_confidence, self.nlu_threshold,
                                   self.fallback_action_name))
            # we set this to 1.1 to make sure fallback overrides
            # the memoization policy
            result = self.fallback_scores(domain)
        else:
            # NLU confidence threshold is met, so
            # predict fallback action with confidence `core_threshold`
            # if this is the highest confidence in the ensemble,
            # the fallback action will be executed.
            result = self.fallback_scores(domain, self.core_threshold)
            try:
                if tracker.latest_action_name != nlu_data["intent"].get('name'):
                    if nlu_data["intent"].get('confidence') > self.core_threshold:
                        idx = domain.index_for_action("utter_{}".format(nlu_data["intent"].get('name')))
                        result[idx] = nlu_data["intent"].get('confidence',self.nlu_threshold)
            except Exception as e:
                pass

        return result
```
I'm not sure if it should be in the main repository so I'll not open a PR for that, at least not until someone validate that assumption.
The code is working fine now, really solid behavior, with this model:
```python
#Env Vars
EPOCHS              = int(os.getenv('EPOCHS', 30))
BATCH_SIZE          = int(os.getenv('BATCH_SIZE', 10))
VALIDATION_SPLIT    = float(os.getenv('VALIDATION_SPLIT', 0.2))
NLU_THRESHOLD       = float(os.getenv('NLU_THRESHOLD', 0.6))
CORE_THRESHOLD      = float(os.getenv('CORE_THRESHOLD', 0.6))
MAX_HISTORY         = int(os.getenv('MAX_HISTORY', 2))
FB_ACTION_NAME = str(os.getenv('FALLBACK_ACTION_NAME', 'utter_default'))
AUGMENTATION        = int(os.getenv('AUGMENTATION', 50))

def train_core(domain_file="bot/domain.yml",
                model_path="bot/models/dialogue",
                training_data_file="bot/data/stories"):
    
    MemoizationPolicy.USE_NLU_CONFIDENCE_AS_SCORE = True

    _keras = KerasPolicy(
                FullDialogueTrackerFeaturizer(
                    LabelTokenizerSingleStateFeaturizer()
                )
            )

    agent = Agent(domain_file,
                policies=[
                    _keras,
                    MemoizationPolicy(max_history=MAX_HISTORY),
                    CustomFallbackPolicy(
                        fallback_action_name=FB_ACTION_NAME,
                        nlu_threshold=NLU_THRESHOLD,
                        core_threshold=CORE_THRESHOLD)]
            )

    training_data = agent.load_data(training_data_file,augmentation_factor=AUGMENTATION)
    agent.train(
        training_data,
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        validation_split=VALIDATION_SPLIT
    )

    agent.persist(model_path)
    return agent
```

thanks for your support.
