### ISSUE TITLE
train_online.py error 

### ISSUE THREAD

**Issue by ztavlas** [RasaHQ/rasa_core#1301]
**Rasa Core version**: 0.11.1

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): Windows

**Issue**: when i use, train_online.py like this :
from rasa_core.training import online

agent.train(data,
                       batch_size=50,
                       epochs=200,
                       max_training_samples=300)				   
    online.run_online_learning(agent)

i am getting : 
    online.run_online_learning(agent)
AttributeError: module 'rasa_core.training.online' has no attribute 'run_online_learning'

and when i use 

from rasa_core.interactive import interactive

agent.train(data,
                       batch_size=50,
                       epochs=200,
                       max_training_samples=300)			
interactive.run_interactive_learning(agent)

i am getting : 
    from rasa_core.interactive import interactive
ModuleNotFoundError: No module named 'rasa_core.interactive'

which one is correct and how can i solve my problem ?

Thanks.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by ztavlas** [comment]
Thanks for your help.

i updated my rasa_core and the latest versions :

rasa-core==0.11.12
rasa-core-sdk==0.11.5
rasa-nlu==0.13.7

But i still have the same problem : 

>> from rasa_core.interactive import interactive
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'rasa_core.interactive'

is there anything else i can do ?

Thanks.

**Comment by ztavlas** [comment]
> upgrade to the latest 0.11 version please, that's when we renamed it to interactive learning, then the import should work


Thanks for your help.

i updated my rasa_core and the latest versions :

rasa-core==0.11.12
rasa-core-sdk==0.11.5
rasa-nlu==0.13.7

But i still have the same problem :

from rasa_core.interactive import interactive
Traceback (most recent call last):
File "", line 1, in 
ModuleNotFoundError: No module named 'rasa_core.interactive'

is there anything else i can do ?

Thanks.

**Comment by akelad** [comment]
it's `rasa_core.training.interactive` i believe

**Comment by ztavlas** [comment]
> it's `rasa_core.training.interactive` i believe

thanks for your comment. i could pass the step but now i am getting another import error.

How can i fix this?

Regards,


C:\Anaconda3\envs\chatbot3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train_online.py", line 15, in <module>
    from rasa_core.training.interactive import interactive
  File "C:\Anaconda3\envs\chatbot3\lib\site-packages\rasa_core\training\interactive.py", line 29, in <module>
    from rasa_core.constants import (
ImportError: cannot import name 'REQUESTED_SLOT'

**Comment by akelad** [comment]
you seem to be using conflicting versions somehow. are you working with the master version of the repo? if yes then you need to reinstall rasa_core
