### ISSUE TITLE
docker-compose yml doesn't seem to work for me

### ISSUE THREAD

**Issue by hypnotisttom** [RasaHQ/rasa_core#1459]
**Rasa Core version**: using compose file as-is, which is set up to pull 'latest'

**Python version**: issue is related to docker-compose; python doesn't come into play

**Operating system** (windows, osx, ...): OSX - Running docker 2.0.0.0-mac81 (29211) on Stable

**Issue**: docker-compose file at https://github.com/RasaHQ/rasa_core/blob/master/docker/docker-compose.yml doesn't seem to work as-is

Getting this:

`Creating network "rt3_rasa-network" with the default driver
Creating rt3_action_server_1 ... done
Creating rt3_rasa_nlu_1      ... done
Creating rt3_duckling_1      ... done
Creating rt3_rasa_core_1     ... done
Attaching to rt3_action_server_1, rt3_duckling_1, rt3_rasa_nlu_1, rt3_rasa_core_1
action_server_1  | INFO:__main__:Starting action endpoint server...
action_server_1  | ERROR:rasa_core_sdk.executor:Failed to register package 'actions.actions'.
action_server_1  | Traceback (most recent call last):
action_server_1  |   File "/app/rasa_core_sdk/executor.py", line 144, in register_package
action_server_1  |     self._import_submodules(package)
action_server_1  |   File "/app/rasa_core_sdk/executor.py", line 131, in _import_submodules
action_server_1  |     package = importlib.import_module(package)
action_server_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
action_server_1  |     return _bootstrap._gcd_import(name[level:], package, level)
action_server_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
action_server_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
action_server_1  |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
action_server_1  | ModuleNotFoundError: No module named 'actions.actions'
action_server_1  | INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)
rasa_nlu_1       | 2018-12-07 15:51:50+0000 [-] Log opened.
rasa_nlu_1       | 2018-12-07 15:51:50+0000 [-] Site starting on 5000
rasa_nlu_1       | 2018-12-07 15:51:50+0000 [-] Starting factory <twisted.web.server.Site object at 0x7f9af0690e48>
duckling_1       | no port specified, defaulting to port 8000
duckling_1       | Listening on http://0.0.0.0:8000
rasa_core_1      | 2018-12-07 15:51:52 INFO     root  - Rasa process starting
rasa_core_1      | Traceback (most recent call last):
rasa_core_1      |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
rasa_core_1      |     "__main__", mod_spec)
rasa_core_1      |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
rasa_core_1      |     exec(code, run_globals)
rasa_core_1      |   File "/app/rasa_core/run.py", line 238, in <module>
rasa_core_1      |     _endpoints = AvailableEndpoints.read_endpoints(cmdline_args.endpoints)
rasa_core_1      |   File "/app/rasa_core/utils.py", line 579, in read_endpoints
rasa_core_1      |     endpoint_file, endpoint_type="nlg")
rasa_core_1      |   File "/app/rasa_core/utils.py", line 518, in read_endpoint_config
rasa_core_1      |     content = read_yaml_file(filename)
rasa_core_1      |   File "/app/rasa_core/utils.py", line 315, in read_yaml_file
rasa_core_1      |     return read_yaml_string(read_file(filename))
rasa_core_1      |   File "/app/rasa_core/utils.py", line 355, in read_file
rasa_core_1      |     with io.open(filename, encoding=encoding) as f:
rasa_core_1      | FileNotFoundError: [Errno 2] No such file or directory: 'config/endpoints.yml'
rt3_rasa_core_1 exited with code 1`

I searched to see if there was additional prep work needed or if anyone else reported docker-compose issues, and nothing came up.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by avdhut08** [comment]
try with following command in docker-compose file:
command:
    - start
    - -d
    - ./model
    - -c
    - rest
    - -u
    - current/nlu
    - --endpoints
    - /app/config/endpoints.yml

**Comment by wochinge** [comment]
@hypnotisttom Did you provide the required endpoint configuration in `./rasa-app-data/config`? Please also have a look at these docs to make sure you provided all required config files: https://rasa.com/docs/core/docker_walkthrough/

**Comment by avdhut08** [comment]
same issue for action_server service in docker-compose file

getting this:-


 ERROR:rasa_core_sdk.executor:Failed to register package 'actions.actions'.
 Traceback (most recent call last):
   File "/app/rasa_core_sdk/executor.py", line 144, in register_package
     self._import_submodules(package)
   File "/app/rasa_core_sdk/executor.py", line 131, in _import_submodules
     package = importlib.import_module(package)
   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
 ModuleNotFoundError: No module named 'actions.actions'

though i added __init__.py in actions directory

**Comment by avdhut08** [comment]
same issue for action_server service in docker-compose file
i wrote service like this in docker-compose 
  action_server:
      image: rasa/rasa_core_sdk:latest
      networks: ['rasa-network']
      volumes:
         - ./actions:/app/actions
      ports:
       - "5055:5055"
getting this:-

ERROR:rasa_core_sdk.executor:Failed to register package 'actions.actions'.
Traceback (most recent call last):
File "/app/rasa_core_sdk/executor.py", line 144, in register_package
self._import_submodules(package)
File "/app/rasa_core_sdk/executor.py", line 131, in _import_submodules
package = importlib.import_module(package)
File "/usr/local/lib/python3.6/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 994, in _gcd_import
File "", line 971, in _find_and_load
File "", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'actions.actions'

though i added init.py in actions directory

**Comment by wochinge** [comment]
@avdhut08 You have to add `__init__.py`. How does your folder structure look like?

**Comment by avdhut08** [comment]
sorry __init__.py only I added ….so it's typing mistake...

my folder structure like:-

-app -- root folder
  -actions
     -- __init__.py
     -- actions.py
  - bot
     -- agent.py
  - model
    --dialogue folder
  - Dockerfile
  - docker-compose.yml

**Comment by avdhut08** [comment]
sorry init.py only I added ….so it's typing mistake...
my folder structure like:-
-app -- root folder
    - actions
         -- init.py
         -- actions.py
    - bot
         -- agent.py
    - model
        --dialogue folder
    - Dockerfile
    - docker-compose.yml

**Comment by avdhut08** [comment]
sorry __init__.py.  only I added ….so it's typing mistake...
my folder structure like:-
-app -- root folder
- actions
-- init.py
-- actions.py
- bot
-- agent.py
- model
--dialogue folder
- Dockerfile
- docker-compose.yml

**Comment by avdhut08** [comment]
sorry __init__.py only I added ….so it's typing mistake...
my folder structure like:-
-app -- root folder
    - actions
         -- __init__.py
         -- actions.py
    - bot
         -- agent.py
    - model
        --dialogue folder
    - Dockerfile
    - docker-compose.yml

**Comment by avdhut08** [comment]
sorry __init__.py only I added ….so it's typing mistake...
my folder structure like:-
-app -- root folder
- actions
-- __init__.py
-- actions.py
- bot
-- agent.py
- model
--dialogue folder
- Dockerfile
- docker-compose.yml

**Comment by avdhut08** [comment]
sorry `__init__.py` only I added ….so it's typing mistake...
my folder structure like:-
-app -- root folder
- actions
--  `__init__.py`
-- actions.py
- bot
-- agent.py
- model
--dialogue folder
- Dockerfile
- docker-compose.yml

**Comment by hypnotisttom** [comment]
Generally speaking, docker images are supposed to be immutable, and docker-compose is supposed to provide the necessary run config to the images.  From this thread, it appears the Rasa images don't run in an immutable fashion, and docker-compose is injecting configs into what would ideally be an immutable image.

It appears the missing link to my problem was the misconception that the Rasa images weren't designed to be immutable.  From my perspective, I was expecting the images to provide some sort of immutable configuration that if I wanted to override with a compose file, I could mount the volumes, "docker cp" the config files over, and edit them from there.  Instead, it sounds like I'll take an approach to building immutable images for my workload using the Dockerfiles themselves.  Now, I just need help understanding which ones I should be using for this purpose...

Is this one correct for Core?: https://github.com/RasaHQ/rasa_core/blob/master/Dockerfile

Which Dockerfile is correct for NLU?  I see a bunch here: https://github.com/RasaHQ/rasa_nlu/tree/master/docker

Thanks for the link to the docker setup @wochinge.  I was at https://rasa.com/docs/core/installation/#using-docker-compose which doesn't seem to imply it won't work as-is, and your link provides the missing details - I appreciate it!

Tom

**Comment by avdhut08** [comment]
@wochinge please respond to my question...

**Comment by wochinge** [comment]
@avdhut08 I just tried with a minimal docker-compose and actions file and it works fine. So I guess you are either not mapping the volumes properly or your python module is invalid.
```yaml
version: '3.0'

services:
  action_server:
    image: rasa/rasa_core_sdk:latest
    volumes:
    - ./actions:/app/actions
    ports:
    - "5055:5055"
```
and a minimal actions.py
```python
from rasa_core_sdk import Action

class ActionTest(Action):

    def name(self):
        return "action_test"

    def run(self, dispatcher, tracker, domain):
        return []
```

**Comment by wochinge** [comment]
@hypnotisttom 
I see what you mean and will discuss it with the team. Maybe we could include trained example models / actions

**Comment by avdhut08** [comment]
Thanks for your response @wochinge ... the error is gone... but i import pandas in action.py file so while docker-compose up i am getting module not found pandas and i can't import python module from other subdirectory also in action.py file

**Comment by avdhut08** [comment]
Thanks for your response @wochinge ... the error is gone... i wrote import pandas in action.py file so while docker-compose up i am getting module not found pandas and i can't import python module from other sub directory in action.py file

**Comment by wochinge** [comment]
@avdhut08 Please read this https://rasa.com/docs/core/docker_walkthrough/#adding-custom-dependencies and ask further questions in our [forum](https://forum.rasa.com/).

I keep this issue open since @hypnotisttom suggestion is up for discussion.

**Comment by tremulaes** [comment]
I'm working through the [docker compose tutorial](https://rasa.com/docs/core/docker_walkthrough/) now and ran into no issues until I tried to make any changes to the model. After attempting to retrain the NLU, the server runs but only returns the 'did not understand' empty list response `[]`. I'm gonna keep going through Rasa docs, but I have a few thoughts:

* The differences between the [installation page docker section](https://rasa.com/docs/core/installation/#compose-file-example) and the actual [docker walkthrough](https://rasa.com/docs/core/docker_walkthrough/) are confusing; it may be more straightforward to replace the docker section on the installation page with a link directly to the docker walkthrough
* A separate repo that can be cloned, setup with the minimum required commands, and manually verified either through curl or through a shell loop (i wrote a quick script in ruby to help) would be very beneficial and I think it'll help close the gap that @hypnotisttom mentions. This also lines up with how I typically start using docker with a new tech stack (i use docker regularly for work)
* Some instructions use the `docker-compose run` command and others use the `docker` command with a ton of args; this is a little confusing especially when trying to debug if issues you're having are due to config problems or not
* Adding an architectural diagram showing how the different containers work together would help a ton for newbies
* Adding tips for debugging would be really helpful- while it's helpful to know that a response of `[]` means the bot doesn't understand what I'm saying, with the multiple components of the Core+NLU+ActionServer+Duckling+TrackerStore it isn't very clear where to even begin trying to find the problem
* Following the tutorial exactly produced a ton of warning messages in the compose logs; I have no idea if that means that something is wrong or if they're expected for a small data set. Googling for the warnings was not particularly useful
* A short 'next steps' section could be really helpful for those who want to take the environment setup by the tutorial and start their own development directly in it (which I suspect is pretty common). The docs site has a lot of good info but very little talks about docker-compose and how development completely inside of compose may differ from local-environment development which can be a little confusing

All in all it's very helpful to have the compose walkthrough so thanks for providing it.

**Comment by wochinge** [comment]
@tremulaes Thanks for your helpful suggestions!
@JustinaPetr
