### ISSUE TITLE
Exporting interactive training session failes if intent 'None' appears during training

### ISSUE THREAD

**Issue by smn-snkl** [RasaHQ/rasa_core#1465]
**Rasa Core version**:
0.12.x
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
ubuntu
**Issue**:
Exporting fails if e.g. during a FormAction you only provide an answer for a slot, without assigning the answer to an intent. In this case the story has an element like this:

> * shopping.add_items_to_wishlist
>     - form_shopping.search_items
>     - form{"name": "form_shopping.search_items"}
>     - slot{"requested_slot": "shopping.item"}
> * form: None

In that scenario, once you try to quit & export the execution crashes.

I think it should be either OK to not declare an intent or the user should be forced to do it. Otherwise it might crash after a long training session and you need to start all over.

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
Hi, could you please elaborate on: `during a FormAction you only provide an answer for a slot, without assigning the answer to an intent.`?

**Comment by smn-snkl** [comment]
@Ghostvv : After you provide an answer to the form it asks you to confirms e.g. like this, right?

`Is the NLU classification for '3' with intent 'inform' correct?  Yes `

But sometimes it doesn't recognize an intent and then asks:

`Is the NLU classification for '3' with intent None correct?  Yes `

In the second case, where the user confirms the `None` intent, the export failes with `KeyError: 'intent'`. I assume it's because the message has no intent and, thus, the key doesn't exist. Here's the full stacktrace:

```
2018-12-13 10:44:39 ERROR    rasa_core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 1283, in record_messages
    _enter_user_message(sender_id, endpoint)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 1131, in _enter_user_message
    lambda a: not a["message"])
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 309, in _ask_questions
    should_retry = _ask_if_quit(sender_id, endpoint)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 615, in _ask_if_quit
    _write_nlu_to_file(nlu_path, evts)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 793, in _write_nlu_to_file
    f.write(nlu_data.as_markdown())
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_nlu/training_data/training_data.py", line 144, in as_markdown
    return MarkdownWriter().dumps(self)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_nlu/training_data/formats/markdown.py", line 170, in dumps
    md += self._generate_training_examples_md(training_data)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_nlu/training_data/formats/markdown.py", line 180, in _generate_training_examples_md
    key=lambda k: k['intent'])
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_nlu/training_data/formats/markdown.py", line 180, in <lambda>
    key=lambda k: k['intent'])
KeyError: 'intent'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/envs/env/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/env/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 1283, in record_messages
    _enter_user_message(sender_id, endpoint)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 1131, in _enter_user_message
    lambda a: not a["message"])
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 309, in _ask_questions
    should_retry = _ask_if_quit(sender_id, endpoint)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 615, in _ask_if_quit
    _write_nlu_to_file(nlu_path, evts)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_core/training/interactive.py", line 793, in _write_nlu_to_file
    f.write(nlu_data.as_markdown())
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_nlu/training_data/training_data.py", line 144, in as_markdown
    return MarkdownWriter().dumps(self)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_nlu/training_data/formats/markdown.py", line 170, in dumps
    md += self._generate_training_examples_md(training_data)
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_nlu/training_data/formats/markdown.py", line 180, in _generate_training_examples_md
    key=lambda k: k['intent'])
  File "/opt/conda/envs/env/lib/python3.6/site-packages/rasa_nlu/training_data/formats/markdown.py", line 180, in <lambda>
    key=lambda k: k['intent'])
KeyError: 'intent'
```

**Comment by Ghostvv** [comment]
and it's not related to the `FromAction` right?

**Comment by smn-snkl** [comment]
Yeah, you're probably right. I just realized it during the FormAction because I didn't check whether the intent was right for the form, since the intent shouldn't matter while the Form is active, right?

**Comment by Ghostvv** [comment]
it depends on how you implement `validation` logic in the forms, but intent `None` is not a good idea

**Comment by smn-snkl** [comment]
I agree, but if you have the slot extracted from the text, you don't really care about the intent, and if you miss out on correcting the intent, your training session just abruptly crashes and you lose all your progress. Maybe it's better to have a warning there and force the user to correct the intent then?

**Comment by Ghostvv** [comment]
yes, I agree if intent is classified as `None` during interactive learning, a user should be forced to set a proper intent
