### ISSUE TITLE
Error rasa_core.training.interactive -  An exception occurred while recording messages. 

### ISSUE THREAD

**Issue by CawaKharkov** [RasaHQ/rasa_core#1499]
**Rasa Core version**: rasa-core           0.12.3

**Python version**:  Python 2.7.15rc1

**Operating system** (windows, osx, ...): Ubuntu 18.04.1 LTS

**Issue**:
Im trying to use interactive learing by running :
```bash
python -m rasa_core.train \
  interactive -o models/dialogue \
  -d weather_domain.yml -s ./data/stories.md \
  --nlu models/nlu/default/weathernlu \
  --endpoints endpoints.yml
```

**Content of domain file** (if used & relevant):
```yaml
slots:
  location:
    type: text


intents:
 - greet
 - goodbye
 - inform


entities:
 - location

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_ask_location:
    - 'In what location?'


actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_location
 - actions.ActionWeather
```

It's starts running and after I sending sirft message and trying to save, getting error:

```bash
Bot loaded. Visualisation at http://localhost:5005/visualization.html.
Type a message and press enter (press 'Ctr-c' to exit).                                                                                                       
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 4319.57it/s, # trackers=1]
? Next user input (Ctr-c to abort):  hi
? Is the NLU classification for 'hi' with intent 'greet' correct?  Yes
------
Chat History

 #    Bot                        You        
────────────────────────────────────────────
 1    action_listen                         
────────────────────────────────────────────
 2                                       hi 
                         intent: greet 0.85 


Current slots: 
        location: None

------
2018-12-18 16:10:29 ERROR    rasa_core.training.interactive - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/home/cawa/rasa/supBot1/venv/local/lib/python2.7/site-packages/rasa_core/training/interactive.py", line 1286, in record_messages
    finetune, sender_ids, plot_file)
  File "/home/cawa/rasa/supBot1/venv/local/lib/python2.7/site-packages/rasa_core/training/interactive.py", line 863, in _predict_till_next_listen
    unconfirmed=[ActionExecuted(action_name)])
  File "/home/cawa/rasa/supBot1/venv/local/lib/python2.7/site-packages/rasa_core/training/interactive.py", line 1220, in _plot_trackers
    max_history=2)
  File "/home/cawa/rasa/supBot1/venv/local/lib/python2.7/site-packages/rasa_core/training/visualization.py", line 435, in visualize_neighborhood
    d["class"] = "dashed active"
TypeError: 'tuple' object does not support item assignment
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/cawa/rasa/supBot1/venv/local/lib/python2.7/site-packages/rasa_core/training/interactive.py", line 1286, in record_messages
    finetune, sender_ids, plot_file)
  File "/home/cawa/rasa/supBot1/venv/local/lib/python2.7/site-packages/rasa_core/training/interactive.py", line 863, in _predict_till_next_listen
    unconfirmed=[ActionExecuted(action_name)])
  File "/home/cawa/rasa/supBot1/venv/local/lib/python2.7/site-packages/rasa_core/training/interactive.py", line 1220, in _plot_trackers
    max_history=2)
  File "/home/cawa/rasa/supBot1/venv/local/lib/python2.7/site-packages/rasa_core/training/visualization.py", line 435, in visualize_neighborhood
    d["class"] = "dashed active"
TypeError: 'tuple' object does not support item assignment

```

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hi @CawaKharkov!

OK, something is going wrong with the visualization.  Can you post your `endpoints.yml` file please?  Have you tried looking at `http://localhost:5005/visualization.html` before it crashed for some insight?

I tried to replicate this error but sadly couldn't.  As a first pass at a solution, please ensure your dependencies are correct by running `pip install -r requirements.txt` in the `rasa_core` directory.

**Comment by CawaKharkov** [comment]
It seems that was a problem with some version of rasa nlu, I've changed to the `rasa_nlu== 0.13.7` and now its working fine.

**Comment by akelad** [comment]
@gaurvipul please create a new issue

**Comment by swapbagal1** [comment]
Any help will be appreciated ASAP.
@CawaKharkov  My issue is not solved even after changing rasa nlu version and retraining the model.

@akelad @gaurvipul 
I am also facing same with rasa_nlu=0.14.1, rasa_nlu=0.13.7, rasa_nlu=0.14.3
(base) C:\Users\swapnali_bagal\Desktop\PROJECT-17-19\Bot1_fullcode>python train_interactive.py
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 1873.08it/s, # trackers=1]
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 2229.53it/s, # trackers=4]
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 468.43it/s, # trackers=20]
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 390.37it/s, # trackers=20]
Processed actions: 25it [00:00, 3977.30it/s, # examples=15]
2019-02-26 18:00:01.261742: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
masking (Masking)            (None, 5, 16)             0
_________________________________________________________________
lstm (LSTM)                  (None, 32)                6272
_________________________________________________________________
dense (Dense)                (None, 11)                363
_________________________________________________________________
activation (Activation)      (None, 11)                0
=================================================================
Total params: 6,635
Trainable params: 6,635
Non-trainable params: 0
_________________________________________________________________
INFO:rasa_core.policies.keras_policy:Fitting model with 169 total samples and a validation split of 0.1
Epoch 1/3
169/169 [==============================] - 1s 4ms/step - loss: 2.3712 - acc: 0.1657
Epoch 2/3
169/169 [==============================] - 0s 104us/step - loss: 2.2820 - acc: 0.4201
Epoch 3/3
169/169 [==============================] - 0s 103us/step - loss: 2.2147 - acc: 0.4734
INFO:rasa_core.policies.keras_policy:Done fitting keras policy model
INFO:rasa_core.training.interactive:Rasa Core server is up and running on http://localhost:5005
Bot loaded. Visualisation at http://localhost:5005/visualization.html.
Type a message and press enter (press 'Ctr-c' to exit).
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 4001.24it/s, # trackers=1]
? Next user input (Ctr-c to abort): bye
? Is the NLU classification for 'bye' with intent 'goodbye' correct?  Yes
------
Chat History

 #    Bot                          You
──────────────────────────────────────────────
 1    action_listen
──────────────────────────────────────────────
 2                                        bye
                         intent: goodbye 0.77


Current slots:
        location: None

------
ERROR:rasa_core.training.interactive:An exception occurred while recording messages.
Traceback (most recent call last):
  File "C:\Users\swapnali_bagal\AppData\Roaming\Python\Python36\site-packages\rasa_core\training\interactive.py", line 1219, in record_messages
    finetune, sender_ids, plot_file)
  File "C:\Users\swapnali_bagal\AppData\Roaming\Python\Python36\site-packages\rasa_core\training\interactive.py", line 821, in _predict_till_next_listen
    unconfirmed=[ActionExecuted(action_name)])
  File "C:\Users\swapnali_bagal\AppData\Roaming\Python\Python36\site-packages\rasa_core\training\interactive.py", line 1154, in _plot_trackers
    max_history=2)
  File "C:\Users\swapnali_bagal\AppData\Roaming\Python\Python36\site-packages\rasa_core\training\visualization.py", line 430, in visualize_neighborhood
    d["class"] = "dashed active"
TypeError: 'tuple' object does not support item assignment
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\swapnali_bagal\AppData\Roaming\Python\Python36\site-packages\rasa_core\training\interactive.py", line 1219, in record_messages
    finetune, sender_ids, plot_file)
  File "C:\Users\swapnali_bagal\AppData\Roaming\Python\Python36\site-packages\rasa_core\training\interactive.py", line 821, in _predict_till_next_listen
    unconfirmed=[ActionExecuted(action_name)])
  File "C:\Users\swapnali_bagal\AppData\Roaming\Python\Python36\site-packages\rasa_core\training\interactive.py", line 1154, in _plot_trackers
    max_history=2)
  File "C:\Users\swapnali_bagal\AppData\Roaming\Python\Python36\site-packages\rasa_core\training\visualization.py", line 430, in visualize_neighborhood
    d["class"] = "dashed active"
TypeError: 'tuple' object does not support item assignment

**Comment by parth2411** [comment]
similar crash is occuring to me
log: https://pastebin.com/rxJNByuk
Rasa NLU Version : 0.14.4
Rasa Core Version : 0.13.2

**Comment by samrudh** [comment]
Any resolution of this issue? It looks like it is marked closed.

**Comment by akelad** [comment]
Please create new issues, the original issue was resolved
