### ISSUE TITLE
Webhook error

### ISSUE THREAD

**Issue by DarrenFYau** [RasaHQ/rasa_core#1544]
**Rasa Core version**:
0.12.3 
**Python version**: 
Python 2.7.6
**Operating system** (windows, osx, ...):
Mac OS
**Issue**:
  I am unable to process messages on facebook.
 
 I am using an endpoint for my actions, and using a webhook to connect to messenger, but am unable to have a response for my message. 

This is the specific error I am getting 

2019-01-08 07:24:53 INFO     root  - Rasa Core server is up and running on http://localhost:6000
2019-01-08 07:25:00 WARNING  py.warnings  - /usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

2019-01-08 07:25:00 ERROR    rasa_core.channels.facebook  - Exception when trying to handle webhook for facebook message.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/channels/facebook.py", line 85, in _handle_user_message
    self.on_new_message(user_msg)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/agent.py", line 317, in handle_message
    return processor.handle_message(message)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 86, in handle_message
    self._predict_and_execute_next_action(message, tracker)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 305, in _predict_and_execute_next_action
    action, policy, confidence = self.predict_next_action(tracker)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 168, in predict_next_action
    probabilities, policy = self._get_next_action_probabilities(tracker)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 478, in _get_next_action_probabilities
    tracker, self.domain)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/policies/ensemble.py", line 291, in probabilities_using_best_policy
    if (result.index(max_confidence) ==
AttributeError: 'NoneType' object has no attribute 'index'
127.0.0.1 - - [2019-01-08 07:25:00] "POST /webhooks/facebook/webhook HTTP/1.1" 200 122 0.004352 

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
@DarrenFYau this doesn't look like a facebook specific error, can you try just running the bot on the command line and see if the same error happens? And then please post the full debug log of the conversation here.

**Comment by DarrenFYau** [comment]
SORRY!!! I made a silly mistake, was running on a dev server, and did not have permissions. I needed to add sudo before starting my webhook. Thanks for your speedy response!

**Comment by DarrenFYau** [comment]
Sorry to bother again, just redeployed, but I am having the same issue again. Don't think I have solved it. I believe that the server is not properly connected to my webhook.

I start by  setting up an endpoint for my actions using 
sudo python -m rasa_core_sdk.endpoint --actions actions

I then set up the server for rasa core using 
sudo python -m rasa_core.run -d models/dialogue -u models/nlu/default/dictionarynlu --port 6000 
--credentials credentials.yml --endpoint endpoints.yml --enable_api

When I message the bot I get the following error with no response from the actions endpoint.

2019-01-09 00:08:29 ERROR    rasa_core.channels.facebook  - Exception when trying to handle webhook for facebook message.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/channels/facebook.py", line 85, in _handle_user_message
    self.on_new_message(user_msg)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/agent.py", line 317, in handle_message
    return processor.handle_message(message)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 86, in handle_message
    self._predict_and_execute_next_action(message, tracker)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 305, in _predict_and_execute_next_action
    action, policy, confidence = self.predict_next_action(tracker)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 168, in predict_next_action
    probabilities, policy = self._get_next_action_probabilities(tracker)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 478, in _get_next_action_probabilities
    tracker, self.domain)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/policies/ensemble.py", line 291, in probabilities_using_best_policy
    if (result.index(max_confidence) ==
AttributeError: 'NoneType' object has no attribute 'index'
127.0.0.1 - - [2019-01-09 00:08:29] "POST /webhooks/facebook/webhook HTTP/1.1" 200 154 0.004679


When trying to run the bot using the command line, I still get no response from the action endpoint

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/channels/channel.py", line 321, in on_message_wrapper
    on_new_message(message)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/agent.py", line 317, in handle_message
    return processor.handle_message(message)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 86, in handle_message
    self._predict_and_execute_next_action(message, tracker)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 305, in _predict_and_execute_next_action
    action, policy, confidence = self.predict_next_action(tracker)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 168, in predict_next_action
    probabilities, policy = self._get_next_action_probabilities(tracker)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 478, in _get_next_action_probabilities
    tracker, self.domain)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/policies/ensemble.py", line 291, in probabilities_using_best_policy
    if (result.index(max_confidence) ==
AttributeError: 'NoneType' object has no attribute 'index'


It seems to work when training the data where I am explicitly passing in the endpoint.

def run_online(interpreter,
                    domain_file="domain.yml",
                    training_data_file='data/stories.md'):
    action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")
    agent = Agent(domain_file,
                  policies=[MemoizationPolicy(max_history=2), KerasPolicy(max_history=3, epochs=3, batch_size=50)],
                  interpreter=interpreter,
                                  action_endpoint=action_endpoint)


    data = agent.load_data(training_data_file)
    agent.train(data)
    interactive.run_interactive_learning(agent, training_data_file)

    return agent

I will get a response back from the action server

DEBUG:rasa_core_sdk.executor:Received request to run 'action_greet'
DEBUG:root:Greet
Finished Uttering Button
DEBUG:rasa_core_sdk.executor:Successfully ran 'action_greet'
127.0.0.1 - - [2019-01-09 00:50:59] "POST /webhook HTTP/1.1" 200 434 0.001271


The contents of my endpoints.yml file is

action_endpoint:
  url: "http://localhost:5055/webhook"

Is there a way to pass in my endpoints explicitly without using endpoints.yml?

**Comment by DarrenFYau** [comment]
I sent a message "hello", which should preform an action that returns a button template

`class ActionGreet(Action):
    def name(self):
        return 'action_greet'

    def run(self, dispatcher, tracker, domain):
        logger.debug("Greet")

        greet = "Hello, I am Jargon the English Bot. You can ask me anytime to define a word, or press Learn A New Word, and I will teach you something new"

        buttons = [{'title': "Learn A New Word", 'payload': "Random Word"},
                   {'title': "Play A Game", 'payload': "Word Exam"},
                   {'title': "Shiritori", 'payload': "Shiritori"}]

        dispatcher.utter_button_message(greet, buttons)

        return []
`


The logs from Rasa Core Server

`Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/usr/local/lib/python2.7/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning:
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:6000
/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

Exception when trying to handle webhook for facebook message.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/channels/facebook.py", line 85, in _handle_user_message
    self.on_new_message(user_msg)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/agent.py", line 317, in handle_message
    return processor.handle_message(message)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 86, in handle_message
    self._predict_and_execute_next_action(message, tracker)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 305, in _predict_and_execute_next_action
    action, policy, confidence = self.predict_next_action(tracker)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 168, in predict_next_action
    probabilities, policy = self._get_next_action_probabilities(tracker)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 478, in _get_next_action_probabilities
    tracker, self.domain)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/policies/ensemble.py", line 291, in probabilities_using_best_policy
    if (result.index(max_confidence) ==
AttributeError: 'NoneType' object has no attribute 'index'`

The policies I am using to train the data are 

policies:
  - name: KerasPolicy
    epochs: 3
    max_history: 3
  - name: FallbackPolicy
    fallback_action_name: 'action_default'
  - name: MemoizationPolicy
    max_history: 2
  - name: FormPolicy


It was working just a while ago, I don't think the message type of message is the issue. I believe there is some issue with my action endpoint because it does not seem to receive incoming function calls. 

before I was getting a response like
`
DEBUG:rasa_core_sdk.executor:Received request to run 'action_greet'
DEBUG:root:Greet
DEBUG:rasa_core_sdk.executor:Successfully ran 'action_greet'
127.0.0.1 - - [2019-01-09 09:10:51] "POST /webhook HTTP/1.1" 200 434 0.001323
`
But now I'm not getting a response from the actions server.

**Comment by akelad** [comment]
Please format your code with ```
Also, can you please post the full DEBUG logs when you're talking to the bot on the commandline, rather than facebook? I can't tell much about where this error is happening without that

**Comment by DarrenFYau** [comment]
Sorry for not responding. The problem came from training the data. I was passing the config file when training the data. 
sudo python -m rasa_core.train -d domain.yml -s data/stories.md -o models/dialogue -c config.json

When I removed the config file everything seemed to work again.

**Comment by akelad** [comment]
hm, `config.json` -- it should be a yml file, that's probably what was causing the issue
