### ISSUE TITLE
MongoDB Tracker Store Authentication Issue

### ISSUE THREAD

**Issue by krishna-kimo** [RasaHQ/rasa_core#1698]
**Rasa Core version**: 0.13.1

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): OSX

**Issue**: Tried connecting to MongoDB tracker-store using the format given in the docs but getting an Authentication Error. I am using MLab. There is no problem with the credentials as I am able to connect to the remote db using both MongoDB and Pymongo. I am not sure how to approach this problem. 

**Content of domain file** (if used & relevant):
endpoints.yaml
```
action_endpoint:
  url: "http://localhost:5055/webhook"

tracker_store:
  store_type: mongod
  url: mongodb://ds######.mlab.com:######
  #db: <dbname>
  username: <##username with no quotes>
  password: < ##password with no quotes>
```
And here is the error (Traceback) I am getting
```
Traceback (most recent call last):
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/run.py", line 247, in <module>
    None, _endpoints.tracker_store, _broker)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/tracker_store.py", line 40, in find_tracker_store
    **store.kwargs)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/tracker_store.py", line 202, in __init__
    self._ensure_indices()
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/tracker_store.py", line 209, in _ensure_indices
    self.conversations.create_index("sender_id")
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/collection.py", line 1958, in create_index
    self.__create_index(keys, kwargs, session, **cmd_options)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/collection.py", line 1847, in __create_index
    with self._socket_for_writes() as sock_info:
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1058, in _get_socket
    with server.get_socket(self.__all_credentials) as sock_info:
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/pool.py", line 1006, in get_socket
    sock_info.check_auth(all_credentials)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/pool.py", line 677, in check_auth
    auth.authenticate(credentials, self)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/auth.py", line 563, in authenticate
    auth_func(credentials, sock_info)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/auth.py", line 540, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1')
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/auth.py", line 262, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/pool.py", line 579, in command
    unacknowledged=unacknowledged)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/network.py", line 150, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/Users/nkdeepak/anaconda3/envs/rasa/lib/python3.6/site-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.

```

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
Which database are you using to authenticate on? `admin` or a different one? (https://docs.mongodb.com/manual/reference/program/mongo/#cmdoption-mongo-authenticationdatabase)
Is mongo using ssl?

**Comment by krishna-kimo** [comment]
Thanks for the reply. Presently I am trying with the Sandbox of Mlab which doesn't provide SSL. I tried using both the admin database as well as the app db as an authentication database. 
Let me know what else can I check. 

Thanks in advance

**Comment by wochinge** [comment]
@krishna-kimo 
> Let me know what else can I check

I guess you are restricted to certain database names on mlab, right? Did you try setting it to you specific one?

**Comment by krishna-kimo** [comment]
@wochinge  Thanks for the reply

I had checked the documentation but couldn't find anything wrong with the way I configured the endpoints.yml . I moved my backend from Mlab to MongoDB Atlas and with the new configuration, I was able to get it to work. I hadn't gone through in detail but the URL is different for different MongoDB versions and maybe I need to double check that. Thanks for the support. This is the configuration I used for MongoDB 4.0 and it is working now

```
tracker_store:
  store_type: mongod
  url: mongodb+srv://#########.mongodb.net/
  username: #######
  password: #######
  auth_source: admin
```

**Comment by wochinge** [comment]
@krishna-kimo Great that you solved it. Super strange that it does not work with Mlab though 🤔

**Comment by krishna-kimo** [comment]
@wochinge 
A suggestion I would like put forward is, in the documentation of the MongoDB tracker-store 'auth_store' is not mentioned as a parameter. It would be beneficial if it can be added to the list of parameters as pymongo accepts 'authStore' and users might be confused by that. I figured it out only I went through the code.

Thanks in advance

**Comment by RanaMostafaAbdElMohsen** [comment]
I managed to make it work
 tracker_store: 
store_type:mongod 
url: dsXXXX.mlab.com:XXXX 
db: databasename 
username: username 
password: password 
auth_source: databasename

**Comment by wochinge** [comment]
@krishna-kimo Thanks for the suggestion! There is already a PR for that 🚀 : https://github.com/RasaHQ/rasa_core/pull/1746
