### ISSUE TITLE
Internal Server Error as it seems to listen to another port than the one specified

### ISSUE THREAD

**Issue by antoinecomp** [RasaHQ/rasa_core#1714]
**Rasa Core version**:

rasa_core : 0.13.0

**Python version**: 
3.6.7
**Operating system** (windows, osx, ...):
windows10

**Issue**:

I have action server running on port 5055 despite specifying in the [`train_interactive.py`](https://github.com/Swarnalathaa/chatbot/blob/master/chatbot_luxury/train_interactive.py) that `EndpointConfig(url="http://localhost:5055/webhook")`, when running `train_interactive.py` I have an  HTTPError: 

```
(swaenv) C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury>python -m rasa_core_sdk.endpoint --actions action
INFO:__main__:Starting action endpoint server...
INFO:rasa_core_sdk.executor:Registered function for 'action_news'.
INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)
```

Indeed, on the `train_interactive.py` side:

```
(swaenv) C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury>python train_interactive.py
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Processed Story Blocks: 100%|██████████████████████████████████████████| 50/50 [00:00<00:00, 1600.13it/s, # trackers=1]
Processed Story Blocks: 100%|███████████████████████████████████████████| 50/50 [00:00<00:00, 533.49it/s, # trackers=8]
Processed Story Blocks: 100%|███████████████████████████████████████████| 50/50 [00:00<00:00, 340.58it/s, # trackers=9]
Processed Story Blocks: 100%|██████████████████████████████████████████| 50/50 [00:00<00:00, 355.63it/s, # trackers=10]
Processed actions: 83it [00:00, 5311.68it/s, # examples=67]
2019-02-11 15:54:26.342851: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
masking (Masking)            (None, 3, 16)             0
_________________________________________________________________
lstm (LSTM)                  (None, 32)                6272
_________________________________________________________________
dense (Dense)                (None, 11)                363
_________________________________________________________________
activation (Activation)      (None, 11)                0
=================================================================
Total params: 6,635
Trainable params: 6,635
Non-trainable params: 0
_________________________________________________________________
INFO:rasa_core.policies.keras_policy:Fitting model with 83 total samples and a validation split of 0.1
Epoch 1/3
83/83 [==============================] - 1s 13ms/step - loss: 2.4015 - acc: 0.1928
Epoch 2/3
83/83 [==============================] - 0s 0us/step - loss: 2.3625 - acc: 0.1928
Epoch 3/3
83/83 [==============================] - 0s 188us/step - loss: 2.3170 - acc: 0.2892
INFO:rasa_core.policies.keras_policy:Done fitting keras policy model
INFO:rasa_core.training.interactive:Rasa Core server is up and running on http://localhost:5005
Bot loaded. Visualisation at http://localhost:5005/visualization.html.
Type a message and press enter (press 'Ctr-c' to exit).
Processed Story Blocks: 100%|██████████████████████████████████████████| 50/50 [00:00<00:00, 3203.76it/s, # trackers=1]
? Next user input (Ctr-c to abort): Hello
ERROR:rasa_core.server:Caught an exception while logging message.
Traceback (most recent call last):
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\rasa_core\server.py", line 444, in log_message
    tracker = agent.log_message(usermsg)
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\rasa_core\agent.py", line 323, in log_message
    return processor.log_message(message)
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\rasa_core\processor.py", line 121, in log_message
    self._handle_message_with_tracker(message, tracker)
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\rasa_core\processor.py", line 259, in _handle_message_with_tracker
    parse_data = self._parse_message(message)
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\rasa_core\processor.py", line 244, in _parse_message
    parse_data = self.interpreter.parse(message.text)
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\rasa_core\interpreter.py", line 240, in parse
    return self.interpreter.parse(text)
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\rasa_nlu\model.py", line 357, in parse
    component.process(message, **self.context)
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\rasa_nlu\classifiers\sklearn_intent_classifier.py", line 180, in process
    intent_ids, probabilities = self.predict(X)
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\rasa_nlu\classifiers\sklearn_intent_classifier.py", line 222, in predict
    pred_result = self.predict_prob(X)
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\rasa_nlu\classifiers\sklearn_intent_classifier.py", line 210, in predict_prob
    return self.clf.predict_proba(X)
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\sklearn\utils\metaestimators.py", line 118, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\sklearn\model_selection\_search.py", line 508, in predict_proba
    return self.best_estimator_.predict_proba(X)
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\sklearn\svm\base.py", line 622, in _predict_proba
    X = self._validate_for_predict(X)
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\sklearn\svm\base.py", line 478, in _validate_for_predict
    (n_features, self.shape_fit_[1]))
ValueError: X.shape[1] = 300 should be equal to 384, the number of features at training time
ERROR:rasa_core.training.interactive:An exception occurred while recording messages.
Traceback (most recent call last):
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\rasa_core\training\interactive.py", line 1213, in record_messages
    _enter_user_message(sender_id, endpoint)
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\rasa_core\training\interactive.py", line 1068, in _enter_user_message
    send_message(endpoint, sender_id, message)
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\rasa_core\training\interactive.py", line 120, in send_message
    return _response_as_json(r)
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\rasa_core\training\interactive.py", line 93, in _response_as_json
    response.raise_for_status()
  File "C:\Users\antoi\Documents\Programming\Swarna\chatbot\chatbot_luxury\swaenv\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5005/conversations/4718844096784420b35df278bc30ff6f/messages
```

**Content of domain file** (if used & relevant):
```yaml
slots:
  market:
    type: text


intents:
 - greet
 - goodbye
 - inform


entities:
 - market


templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_ask_location:
    - 'In what location?'


actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_location
 - action_news
```

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing  will get back to you about it soon.

**Comment by erohmensing** [comment]
Hi @antoinecomp , I think your HTTP server error comes from the earlier `ERROR:rasa_core.server:Caught an exception while logging message.` Therefore the real error is probably the 

> ValueError: X.shape[1] = 300 should be equal to 384, the number of features at training time

I'm not sure how these shapes got mixed up (I cloned your repo and used it on my machine and it worked fine) -- what versions of `rasa_nlu` and `sklearn` are you running?

**Comment by antoinecomp** [comment]
@erohmensing Yes,

```
rasa-nlu: 0.14.3
>>> print('The scikit-learn version is {}.'.format(sklearn.__version__))
The scikit-learn version is 0.20.2.
```

Thank you for your help !

**Comment by erohmensing** [comment]
@antoinecomp can you try re-training your nlu model and running it again? It's possible that your spacy models are different between your trained model and the one you are running. Do you know if you've downloaded `en_core_web_md`? More info here: https://rasa.com/docs/nlu/master/installation/#great-for-getting-started-spacy-sklearn
<img width="848" alt="screen shot 2019-02-18 at 18 54 42" src="https://user-images.githubusercontent.com/22333512/52968874-e15ff880-33ae-11e9-8cbb-55e7395ebe6c.png">

**Comment by antoinecomp** [comment]
@erohmensing Yes, I installed it. I had an issue with train_init.py before `TypeError: fit() got multiple values for keyword argument 'epochs'`. So I followed [this answer](https://stackoverflow.com/questions/53294681/rasa-chatbot-framework-gives-error-while-training-fit-got-multiple-values-for) which basically modifies keras_policy.py by getting rid of epochs and batch_size and training was ok.

Yet when running train_online.py I still had the same error as before:

```
(chaenv36) C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation>python train_online.py
C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_nlu\extractors\entity_synonyms.py:85: UserWarning: Failed to load synonyms file from './models/current/nlu\entity_synonyms.json'
  "".format(entity_synonyms_file))
C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning:
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
Processed Story Blocks: 100%|████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 2002.88it/s, # trackers=1]
Processed Story Blocks: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 312.64it/s, # trackers=6]
Processed Story Blocks: 100%|████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 139.06it/s, # trackers=12]
Processed Story Blocks: 100%|████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 149.94it/s, # trackers=10]
Processed actions: 44it [00:00, 17643.34it/s, # examples=44]
2019-02-18 23:50:17.631291: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
masking (Masking)            (None, 5, 22)             0
_________________________________________________________________
lstm (LSTM)                  (None, 32)                7040
_________________________________________________________________
dense (Dense)                (None, 11)                363
_________________________________________________________________
activation (Activation)      (None, 11)                0
=================================================================
Total params: 7,403
Trainable params: 7,403
Non-trainable params: 0
_________________________________________________________________
INFO:rasa_core.policies.keras_policy:Fitting model with 101 total samples and a validation split of 0.1
Epoch 1/1
101/101 [==============================] - 1s 11ms/step - loss: 2.4346 - acc: 0.0792
INFO:rasa_core.policies.keras_policy:Done fitting keras policy model
INFO:rasa_core.training.interactive:Rasa Core server is up and running on http://localhost:5005
Bot loaded. Visualisation at http://localhost:5005/visualization.html.
Type a message and press enter (press 'Ctr-c' to exit).
Processed Story Blocks: 100%|████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 2319.68it/s, # trackers=1]
? Next user input (Ctr-c to abort):  Hey
ERROR:rasa_core.server:Caught an exception while logging message.
Traceback (most recent call last):
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_core\server.py", line 437, in log_message
    tracker = agent.log_message(usermsg)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_core\agent.py", line 341, in log_message
    return processor.log_message(message)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_core\processor.py", line 129, in log_message
    self._handle_message_with_tracker(message, tracker)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_core\processor.py", line 269, in _handle_message_with_tracker
    parse_data = self._parse_message(message)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_core\processor.py", line 255, in _parse_message
    parse_data = self.interpreter.parse(message.text)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_core\interpreter.py", line 293, in parse
    return self.interpreter.parse(text)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_nlu\model.py", line 357, in parse
    component.process(message, **self.context)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_nlu\classifiers\sklearn_intent_classifier.py", line 180, in process
    intent_ids, probabilities = self.predict(X)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_nlu\classifiers\sklearn_intent_classifier.py", line 222, in predict
    pred_result = self.predict_prob(X)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_nlu\classifiers\sklearn_intent_classifier.py", line 210, in predict_prob
    return self.clf.predict_proba(X)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\sklearn\utils\metaestimators.py", line 115, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\sklearn\model_selection\_search.py", line 484, in predict_proba
    return self.best_estimator_.predict_proba(X)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\sklearn\svm\base.py", line 594, in _predict_proba
    X = self._validate_for_predict(X)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\sklearn\svm\base.py", line 459, in _validate_for_predict
    (n_features, self.shape_fit_[1]))
ValueError: X.shape[1] = 300 should be equal to 384, the number of features at training time
ERROR:rasa_core.training.interactive:An exception occurred while recording messages.
Traceback (most recent call last):
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_core\training\interactive.py", line 1257, in record_messages
    _enter_user_message(sender_id, endpoint)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_core\training\interactive.py", line 1110, in _enter_user_message
    send_message(endpoint, sender_id, answers["message"])
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_core\training\interactive.py", line 119, in send_message
    return _response_as_json(r)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_core\training\interactive.py", line 92, in _response_as_json
    response.raise_for_status()
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5005/conversations/default/messages
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_core\training\interactive.py", line 1257, in record_messages
    _enter_user_message(sender_id, endpoint)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_core\training\interactive.py", line 1110, in _enter_user_message
    send_message(endpoint, sender_id, answers["message"])
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_core\training\interactive.py", line 119, in send_message
    return _response_as_json(r)
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_core\training\interactive.py", line 92, in _response_as_json
    response.raise_for_status()
  File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5005/conversations/default/messages
```

I tried to install spacy with Sklearn again with sklearn but it didn't changed anything

**Comment by erohmensing** [comment]
Sorry, i'm not sure I was clear. `train_init.py` will just train your core model, have you retrained your nlu model using `nlu_model.py`?

**Comment by erohmensing** [comment]
Try that first -- if that doesn't work, would you try changing the pipeline to `tensorflow_embedding` instead of `spacy_sklearn` (this will require installing the pipeline if you've only installed spacy -- more information again at the link from above) -- That can help us figure out if its a sklearn/spacy problem :)
