### ISSUE TITLE
Checkpoints warning/errors with train compare

### ISSUE THREAD

**Issue by huberrom** [RasaHQ/rasa_core#1726]
**Rasa Core version**: 13.0

**Python version**: 3.6

I have stories with checkpoints, and it doesn't cause a problem during training, but I'm currently comparing two embedding policy and I got the following errors :

```
2019-02-15 18:13:47 WARNING  rasa_core.training.generator  - Unsatisfied start checkpoint 'question_transmettre_facture_justificative' in block 'question_transmettre_facture_justificative_negation'. Remove this checkpoint or add story blocks that end with this checkpoint.
2019-02-15 18:13:47 WARNING  rasa_core.training.generator  - Unsatisfied end checkpoint 'droits_enfant_negation' in block 'story_enfant_couvert_etudes_-21_negation'. Remove this checkpoint or add story blocks that start with this checkpoint.
2019-02-15 18:13:47 WARNING  rasa_core.training.generator  - Unsatisfied end checkpoint 'droits_enfant_negation' in block 'story_enfant_couvert_-21_-28_negation_redemande_age'. Remove this checkpoint or add story blocks that start with this checkpoint.
2019-02-15 18:13:47 WARNING  rasa_core.training.generator  - Unsatisfied end checkpoint 'droits_enfant_negation' in block 'story_enfant_couvert_etudes_-21_negation_redemande_age'. Remove this checkpoint or add story blocks that start with this checkpoint.
2019-02-15 18:13:47 WARNING  rasa_core.training.generator  - Unsatisfied end checkpoint 'droits_enfant_negation' in block 'story_enfant_couvert_-21_-28_negation'. Remove this checkpoint or add story blocks that start with this checkpoint.
```

For example, the first warning comes from this story : 

```
* demande_enfant_etudes_couvert
    - action_poser_questions
    - action_demande_age_enfant
* reponse_age_enfant{"age_enfant": "6"}
    - action_droits_enfant_etudes
> droits_enfant_negation

## droits_enfant_negation
> droits_enfant_negation
* reponse_negative
    - action_negation_droit_enfant
> demande_relance_autre_question

## demande_relance_autre_question
> demande_relance_autre_question
    - action_autre_chose
    - action_listen
    - action_reponse_relance_autre_question
```

This error doesn't occured for the first two rounds (0 and 5% exclusion) and begin at the third (25% exclusion).

I think it's because one of those story is excluded, but I thought the checkpoints would automatically create multiple story, and a few of them would be excluded.

Any idea on this ?

**Comment by huberrom** [comment]
My training compare end up with this error :

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/huberrom/.local/lib/python3.6/site-packages/rasa_core/train.py", line 361, in <module>
    additional_args)
  File "/home/huberrom/.local/lib/python3.6/site-packages/rasa_core/train.py", line 276, in do_compare_training
    additional_arguments)
  File "/home/huberrom/.local/lib/python3.6/site-packages/rasa_core/train.py", line 246, in train_comparison_models
    dump_stories=dump_stories)
  File "/home/huberrom/.local/lib/python3.6/site-packages/rasa_core/train.py", line 190, in train_dialogue_model
    agent.train(training_data, **kwargs)
  File "/home/huberrom/.local/lib/python3.6/site-packages/rasa_core/agent.py", line 520, in train
    **kwargs)
  File "/home/huberrom/.local/lib/python3.6/site-packages/rasa_core/policies/ensemble.py", line 63, in train
    policy.train(training_trackers, domain, **kwargs)
  File "/home/huberrom/.local/lib/python3.6/site-packages/rasa_core/policies/embedding_policy.py", line 953, in train
    training_data.y)
  File "/home/huberrom/.local/lib/python3.6/site-packages/rasa_core/policies/embedding_policy.py", line 362, in _create_tf_session_data
    Y = self._action_features_for_Y(actions_for_Y)
  File "/home/huberrom/.local/lib/python3.6/site-packages/rasa_core/policies/embedding_policy.py", line 323, in _action_features_for_Y
    for action_ids in actions_for_Y])
  File "/home/huberrom/.local/lib/python3.6/site-packages/rasa_core/policies/embedding_policy.py", line 323, in <listcomp>
    for action_ids in actions_for_Y])
TypeError: 'numpy.int64' object is not iterable
```

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon.

**Comment by Ghostvv** [comment]
this happens because exclusion happens on the written story blocks level, rather than generated full story trackers

**Comment by huberrom** [comment]
So there is no way to use both checkpoints and rasa_core.train compare with exclusion ?

**Comment by Ghostvv** [comment]
You can generate training trackers from full stories and then write a script to export these trackers as story file

**Comment by huberrom** [comment]
Hum I see, I'll try to find how to generate those trackers. The error comes from this too ?

Another issue I have with the train compare, is that when I try to compare two embedding policy with differents parameters, the second policy will override the first model because it has the same name :

```
2019-02-17 16:08:02 INFO     root  - Starting to train EmbeddingPolicy round 7/7 with 95% exclusion
Processed Story Blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 2118.12it/s, # trackers=1]2019-02-17 16:08:07 INFO     rasa_core.policies.embedding_policy  - Accuracy is updated every 20 epochs
Epochs: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2000/2000 [02:39<00:00, 12.54it/s, loss=0.018, acc=1.000]2019-02-17 16:10:46 INFO     rasa_core.policies.embedding_policy  - Finished training embedding policy, loss=0.018, train accuracy=1.000
2019-02-17 16:10:47 INFO     rasa_core.agent  - Persisted model to 'chatbot-rasa-core/comparison_models/run_3/EmbeddingPolicy7'
2019-02-17 16:10:47 INFO     root  - Starting to train EmbeddingPolicy round 7/7 with 95% exclusion
Processed Story Blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 2852.88it/s, # trackers=1]2019-02-17 16:10:52 INFO     rasa_core.policies.embedding_policy  - Accuracy is updated every 20 epochs
Epochs: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [01:13<00:00, 13.55it/s, loss=0.034, acc=1.000]2019-02-17 16:12:05 INFO     rasa_core.policies.embedding_policy  - Finished training embedding policy, loss=0.034, train accuracy=1.000
2019-02-17 16:12:05 INFO     rasa_core.agent  - Model directory comparison_models/run_3/EmbeddingPolicy7 exists and contains old model files. All files will be overwritten.
2019-02-17 16:12:06 INFO     rasa_core.agent  - Persisted model to 'chatbot-rasa-core/comparison_models/run_3/EmbeddingPolicy7'
```

I tried with the following policies :

```
policies:
  - name: EmbeddingPolicy
    epochs: 1000
    attn_shift_range: 3
    featurizer:
      - name: FullDialogueTrackerFeaturizer
        state_featurizer:
          - name: LabelTokenizerSingleStateFeaturizer
```

```
policies:
  - name: EmbeddingPolicy
    epochs: 2000
    attn_shift_range: 2
    featurizer:
      - name: FullDialogueTrackerFeaturizer
        state_featurizer:
          - name: LabelTokenizerSingleStateFeaturizer
```

I'm new with the embedding policy, so I just wanted to see if there is a huge difference if I change the epoch / attn_shift_range

**Comment by Ghostvv** [comment]
yes, it is a known issue, I did temporally fix here: https://github.com/RasaHQ/rasa_core/blob/94c130320f992b9c6583b72fad5ef07374193f52/rasa_core/train.py#L231

you'll need to modify `evaluate` script from this branch as well

**Comment by huberrom** [comment]
Ok thank you for your time !
