### ISSUE TITLE
Unable to run Rasa Core as a HTTP server

### ISSUE THREAD

**Issue by kianmeng-aft** [RasaHQ/rasa_core#18]
**Rasa Core version** (e.g. `0.7.3`):
Rasa Core - 0.7.1

**Operating system** (windows, osx, ...):
Window 10 64-bit
PIP - 9.0.1
Python - 3.6.3

**Issue**:
I am able to set up rasa and do a "Hello, World" as described on https://core.rasa.ai/installation.html

however , when i am trying `Rasa Core as a HTTP server` (https://core.rasa.ai/http.html) , i keep facing 

```
PS C:\temp\rasa_core>  python -m rasa_core.server -d examples/babi/models/policy/current -u examples/babi/models/nlu/current_py2 -o out.log
Using TensorFlow backend.
2017-10-11 15:56:21.537946: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-11 15:56:21.538093: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
WARNING:rasa_nlu.model:Deprecated use of `Interpreter.load` with a metadata object. If you want to directly pass the metadata, use `Interpreter.create(metadata, ...)`. If you want to load the metadata from file, use `Interpreter.load(model_dir, ...)
DEBUG:pip.vcs:Registered VCS backend: git
DEBUG:pip.vcs:Registered VCS backend: hg
DEBUG:pip.pep425tags:Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
DEBUG:pip.pep425tags:Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
DEBUG:pip.pep425tags:Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
DEBUG:pip.pep425tags:Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
DEBUG:pip.vcs:Registered VCS backend: svn
DEBUG:pip.vcs:Registered VCS backend: bzr
INFO:rasa_nlu.components:Couldn't read dev-requirements.txt. Error: [Errno 0] Error: 'rasa_nlu\\..\\alt_requirements\\requirements_dev.txt'
Traceback (most recent call last):
  File "C:\Users\KIANMENG\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\KIANMENG\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\temp\rasa_core\rasa_core\server.py", line 147, in <module>
    cmdline_args.log_file)
  File "C:\temp\rasa_core\rasa_core\server.py", line 71, in __init__
    self.agent = self._create_agent(model_directory, nlu_model)
  File "C:\temp\rasa_core\rasa_core\server.py", line 75, in _create_agent
    return Agent.load(model_directory, nlu_model)
  File "C:\temp\rasa_core\rasa_core\agent.py", line 51, in load
    _interpreter = NaturalLanguageInterpreter.create(interpreter)
  File "C:\temp\rasa_core\rasa_core\interpreter.py", line 27, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "C:\temp\rasa_core\rasa_core\interpreter.py", line 136, in __init__
    os.environ))
  File "C:\Users\KIANMENG\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu-0.10.1-py3.6.egg\rasa_nlu\model.py", line 229, in load
  File "C:\Users\KIANMENG\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu-0.10.1-py3.6.egg\rasa_nlu\model.py", line 252, in create
  File "C:\Users\KIANMENG\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu-0.10.1-py3.6.egg\rasa_nlu\components.py", line 96, in validate_requirements
Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install sklearn
```
I have already installed all the requirements as mention on the installation guide
```
pip install -r requirements.txt
pip install -r dev-requirements.txt
```

As you can see, `sklearn` and the other dependencies are installed 
```
alabaster (0.7.10)
apipkg (1.4)
APScheduler (3.3.1)
argh (0.26.2)
attrs (17.2.0)
Automat (0.6.0)
Babel (2.5.1)
bleach (1.5.0)
boto3 (1.4.4)
botocore (1.5.95)
certifi (2017.7.27.1)
chardet (3.0.4)
click (6.7)
cloudpickle (0.4.0)
colorama (0.3.9)
colorclass (2.2.0)
configargparse (0.12.0)
constantly (15.1.0)
coverage (4.0.3)
cycler (0.10.0)
cymem (1.31.2)
cytoolz (0.8.2)
decorator (4.1.2)
dill (0.2.7.1)
docutils (0.14)
en-core-web-sm (1.2.0)
entrypoints (0.2.3)
execnet (1.4.1)
fakeredis (0.8.2)
Flask (0.12.2)
ftfy (4.4.3)
future (0.16.0)
gevent (1.2.1)
graphviz (0.7.1)
greenlet (0.4.12)
h5py (2.7.0)
html5lib (0.9999999)
hyperlink (17.3.1)
idna (2.6)
imagesize (0.7.1)
incremental (17.5.0)
ipython-genutils (0.2.0)
itsdangerous (0.24)
Jinja2 (2.9.6)
jmespath (0.9.3)
jsonpickle (0.9.4)
jsonschema (2.6.0)
jupyter-core (4.3.0)
keras (2.0.8)
klein (17.2.0)
livereload (2.5.1)
Markdown (2.6.9)
MarkupSafe (1.0)
matplotlib (1.5.3)
mistune (0.7.4)
murmurhash (0.26.4)
nbconvert (5.3.1)
nbformat (4.4.0)
nbsphinx (0.2.13)
networkx (1.11)
numpy (1.13.1)
pandoc (1.0.0b2)
pandocfilters (1.4.2)
pathlib (1.0.1)
pathtools (0.1.2)
pep8 (1.7.0)
pip (9.0.1)
plac (0.9.6)
ply (3.10)
port-for (0.3.1)
preshed (1.0.0)
protobuf (3.4.0)
psutil (5.3.1)
py (1.4.34)
Pygments (2.2.0)
pygraphviz (1.5.dev0)
pymessenger (0.0.7.0)
pyparsing (2.2.0)
pypiwin32 (220)
pyreadline (2.1)
pytest (3.2.3)
pytest-cache (1.0)
pytest-cov (2.5.1)
pytest-flask (0.10.0)
pytest-pep8 (1.0.6)
pytest-services (1.2.1)
pytest-xdist (1.15.0)
python-coveralls (2.9.1)
python-crfsuite (0.9.5)
python-dateutil (2.6.1)
pytz (2017.2)
PyYAML (3.12)
rasa-core (0.7.1, c:\temp\rasa_core)
rasa-nlu (0.10.1, c:\users\kianmeng\appdata\local\programs\python\python36\lib\site-packages\rasa_nlu-0.10.1-py3.6.egg)
redis (2.10.5)
regex (2017.9.23)
requests (2.18.4)
requests-toolbelt (0.8.0)
s3transfer (0.1.11)
scikit-learn (0.19.0)
scipy (0.19.1)
setuptools (36.5.0)
simplejson (3.11.1)
six (1.10.0)
sklearn (0.0)
sklearn-crfsuite (0.3.6)
snowballstemmer (1.2.1)
spacy (1.9.0)
Sphinx (1.6.4)
sphinx-autobuild (0.6.0)
sphinx-rtd-theme (0.2.5b1, c:\temp\rasa_core\src\sphinx-rtd-theme)
sphinxcontrib-versioning (2.2.1)
sphinxcontrib-websupport (1.0.1)
tabulate (0.8.1)
tensorflow (1.3.0)
tensorflow-tensorboard (0.1.8)
termcolor (1.1.0)
testpath (0.3.1)
thinc (6.5.2)
toolz (0.8.2)
tornado (4.5.2)
tqdm (4.11.2)
traitlets (4.3.2)
Twisted (17.9.0)
typing (3.6.2)
tzlocal (1.4)
ujson (1.35)
urllib3 (1.22)
watchdog (0.8.3)
wcwidth (0.1.7)
webencodings (0.5.1)
Werkzeug (0.12.2)
wheel (0.30.0)
wrapt (1.10.11)
zope.interface (4.4.3)
```

Is there anything else that i am missing?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by tmbo** [comment]
When you run `C:\Users\KIANMENG\AppData\Local\Programs\Python\Python36` in an interactive python session, are you able to `import sklearn` ?

**Comment by kianmeng-aft** [comment]
hey tmbo , thanks for the prompt reply.

```
 import sklearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\KIANMENG\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\__init__.py", line 134, in <module>
    from .base import clone
  File "C:\Users\KIANMENG\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\base.py", line 12, in <module>
    from .utils.fixes import signature
  File "C:\Users\KIANMENG\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\utils\__init__.py", line 11, in <module>
    from .validation import (as_float_array,
  File "C:\Users\KIANMENG\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\utils\validation.py", line 18, in <module>
    from ..utils.fixes import signature
  File "C:\Users\KIANMENG\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\utils\fixes.py", line 144, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
  File "C:\Users\KIANMENG\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\sparse\linalg\__init__.py", line 114, in <module>
    from .isolve import *
  File "C:\Users\KIANMENG\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\sparse\linalg\isolve\__init__.py", line 6, in <module>
    from .iterative import *
  File "C:\Users\KIANMENG\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\sparse\linalg\isolve\iterative.py", line 7, in <module>
    from . import _iterative
ImportError: DLL load failed: The specified module could not be found.
```

there is indeed some problem, i tried to google and i reinstalled `scipy` and `scikit-learn` still the same issue...

any idea how can i fix this?

**Comment by kianmeng-aft** [comment]
Found out the issue, its with numpy, i need to install `numpy+mkl` instead .
Closing this , thanks!

**Comment by tmbo** [comment]
@kianmeng-aft mind sharing the commands you ran to resolve the problem? I think a couple other windows users ran into a similar issue with sklearn.

**Comment by kianmeng-aft** [comment]
i downloaded [numpy‑1.13.3+mkl‑cp36‑cp36m‑win_amd64.whl](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy)
 and ran the command :
```
pip install numpy‑1.13.3+mkl‑cp36‑cp36m‑win_amd64.whl
```

basically from what i tested  there are 2 requirements that needs to be changed for windows users....
![image](https://user-images.githubusercontent.com/22811886/31487082-19b307c2-af6c-11e7-97dc-fcc87e5418a2.png)

hope that helps

**Comment by tmbo** [comment]
@kianmeng-aft that is a very useful insight. Mind creating a PR to update these two?

**Comment by kianmeng-aft** [comment]
i tried changing it using ubuntu virtual box , but seems like the `mkl` thingy is only available for window.
![image](https://user-images.githubusercontent.com/22811886/31489265-ae7b1916-af72-11e7-850d-989191648592.png)

so i guess for windows user , we will have to manually change it instead 😞

**Comment by kianmeng-aft** [comment]
right now , i am facing another issue mention in this ticket https://github.com/RasaHQ/rasa_core/issues/23
(tested using ubuntu virtual box and its is ok)

is there by any chance some other windows user already found a fix to this?
[rasa is not windows friendly 😢 ]

**Comment by yipcma** [comment]
I face the same issue on ubuntu 14.04, it doesn't like the numpy or sklearn installed as instructed in the nlu docs.
crossref #108

**Comment by yipcma** [comment]
resolved, by installing tensorflow-gpu

**Comment by imcoolhead** [comment]
I am facing similar issue on unix (RHEL 6.8). 

Exception: Not all required packages are installed. Failed to find the following imports spacy, sklearn. To use this pipeline, you need to install the missing dependencies, e.g. by running:
        > pip install spacy==1.8.2 scikit-learn==0.18.1 scipy==0.19.0 matplotlib==1.5.3

Required dependencies are already installed under  "/opt/rh/python27/root/usr/**lib64**/python2.7/site-packages"  but rasa core is looking under "/opt/rh/python27/root/usr/**lib**/python2.7/site-packages"

I started /opt/rh/python27/root/usr/bin/python in interactive mode and tried import spacy , there is no error.  Also i have been using rasa nlu for few months now and never has any issues. 

/opt/rh/python27/root/usr/bin/python -m rasa_core.run -d models/dialogue -u models/nlu/model_20171117-110732/
INFO:root:Rasa process starting
Using TensorFlow backend.
2017-11-29 23:20:26.434263: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
DEBUG:pip.utils:bz2 module is not available
DEBUG:pip.utils:lzma module is not available
DEBUG:pip.vcs:Registered VCS backend: git
DEBUG:pip.vcs:Registered VCS backend: hg
DEBUG:pip.vcs:Registered VCS backend: svn
DEBUG:pip.vcs:Registered VCS backend: bzr
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/rh/python27/root/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rasa_core/run.py", line 126, in <module>
    cmdline_args.credentials)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rasa_core/run.py", line 105, in main
    agent = Agent.load(model_directory, nlu_model)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rasa_core/agent.py", line 55, in load
    _interpreter = NaturalLanguageInterpreter.create(interpreter)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rasa_core/interpreter.py", line 27, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rasa_core/interpreter.py", line 132, in __init__
    self._load_interpreter()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rasa_core/interpreter.py", line 151, in _load_interpreter
    os.environ))
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rasa_nlu/model.py", line 225, in load
    skip_valdation)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rasa_nlu/model.py", line 248, in create
    components.validate_requirements(model_metadata.pipeline)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/rasa_nlu/components.py", line 92, in validate_requirements
    "> pip install {}".format(" ".join(missing_requirements)))
Exception: Not all required packages are installed. Failed to find the following imports spacy, sklearn. To use this pipeline, you need to install the missing dependencies, e.g. by running:
        > pip install spacy==1.8.2 scikit-learn==0.18.1 scipy==0.19.0 matplotlib==1.5.3
