### ISSUE TITLE
Value Error: Dictionary update sequence element

### ISSUE THREAD

**Issue by jaimet561** [RasaHQ/rasa_core#191]
**Rasa Core version**:
0.7.9
**Python version**: 
Python 2.7.11 (default, Sep 29 2016, 13:33:00)
**Operating system** (windows, osx, ...):
Fedora 23
**Issue**:
I am following the steps found in : 
https://core.rasa.ai/tutorial_basics.html#define-a-domain
when I run the command:
python -m rasa_nlu.train -c nlu_model_config.json --fixed_model_name current
I get error:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/rasa_nlu/train.py", line 122, in <module>
    config = init()
  File "/usr/lib/python2.7/site-packages/rasa_nlu/train.py", line 87, in init
    config = RasaNLUConfig(args.config, os.environ, vars(args))
  File "/usr/lib/python2.7/site-packages/rasa_nlu/config.py", line 80, in __init__
    self.override(file_config)
  File "/usr/lib/python2.7/site-packages/rasa_nlu/config.py", line 181, in override
    abs_path_config = self.make_unicode(self.make_paths_absolute(config, ["path", "response_log"]))
  File "/usr/lib/python2.7/site-packages/rasa_nlu/config.py", line 164, in make_paths_absolute
    abs_path_config = dict(config)
ValueError: dictionary update sequence element #0 has length 5; 2 is required

can anyone help me. Please

**Content of domain file** (if used & relevant):
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy

templates:
  utter_greet:
  - text: "Hey! How are you?"
    buttons:
    - title: "great"
      payload: "great"
    - title: "super sad"
      payload: "super sad"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://cdn77.eatliver.com/wp-content/uploads/2017/10/trump-frog.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"

actions:
  - utter_greet
  - utter_cheer_up
  - utter_did_that_help
  - utter_happy
  - utter_goodbye

**Comment by tmbo** [comment]
whats the content of `nlu_model_config.json`?

**Comment by jaimet561** [comment]
this is the content:
[{
  "pipeline": "spacy_sklearn",
  "path" : "./models",
  "project": "nlu",
  "data" : "./data/nlu.md"
}]

**Comment by tmbo** [comment]
Let's remove the outer `[ ... ]`  and you should be good to go.

**Comment by jaimet561** [comment]
ok. I tried with out the enclosing square braces and got:
```
INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'en'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/rasa_nlu/train.py", line 125, in <module>
    do_train(config)
  File "/usr/lib/python2.7/site-packages/rasa_nlu/train.py", line 111, in do_train
    trainer = Trainer(config, component_builder)
  File "/usr/lib/python2.7/site-packages/rasa_nlu/model.py", line 131, in __init__
    component_name, config)
  File "/usr/lib/python2.7/site-packages/rasa_nlu/components.py", line 327, in create_component
    component = registry.create_component_by_name(component_name, config)
  File "/usr/lib/python2.7/site-packages/rasa_nlu/registry.py", line 160, in create_component_by_name
    return component_clz.create(config)
  File "/usr/lib/python2.7/site-packages/rasa_nlu/utils/spacy_utils.py", line 52, in create
    nlp = spacy.load(spacy_model_name, parser=False)
  File "/usr/lib64/python2.7/site-packages/spacy/__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "/usr/lib64/python2.7/site-packages/spacy/util.py", line 119, in load_model
    raise IOError("Can't find model '%s'" % name)
IOError: Can't find model 'en'
```

**Comment by tmbo** [comment]
make sure to install a spacy language model: `python -m spacy download en`

**Comment by jaimet561** [comment]
oh.. i thought that en was the name of the model (example) but it is actually, like a module.
thanks for your help and time.

**Comment by jaimet561** [comment]
will continue trying
