### ISSUE TITLE
Deprecated module gevent.wsgi

### ISSUE THREAD

**Issue by tupac56** [RasaHQ/rasa_core#460]
**Rasa Core version**: Rasa master

**Python version**: 3.6

**Operating system** : Linux (Docker)

**Issue**: 
Hello there,

I just ran into an issue with gevent: from version 1.3b2 (2018-05-03) of gevent used in file `rasa_core/channels/rest.py`, deprecated module `gevent.wsgi` is removed.

Line 57 should be replaced with : `from gevent.pywsgi import WSGIServer`

*gevent changelog:*
https://github.com/gevent/gevent/blob/7835efdaac3a5c3dcc6997096c454412389dd565/CHANGES.rst#13b2-2018-05-03

Thanks!

**Comment by Walter-Ullon** [comment]
I am still having issues with this building in docker:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/run.py", line 151, in <module>
    cmdline_args.credentials)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/run.py", line 135, in main
    agent.handle_channel(input_channel)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/agent.py", line 126, in handle_channel
    processor.handle_channel(input_channel)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/processor.py", line 60, in handle_channel
    input_channel.start_sync_listening(self.handle_message)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/channels/rest.py", line 36, in start_sync_listening
    self._record_messages(message_handler)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/channels/rest.py", line 57, in _record_messages
    from gevent.wsgi import WSGIServer
ModuleNotFoundError: No module named 'gevent.wsgi'
```

Below is my requirements.txt:
```
rasa_core == 0.8.6
rasa_nlu == 0.11.3
spacy == 2.0.8
pandas == 0.22.0
Jpype1 == 0.6.2
duckling == 1.7.3
sklearn-crfsuite ==0.3.6
```

Any ideas?

**Comment by Walter-Ullon** [comment]
@tmbo per the requirements.txt, we are using Rasa Core 0.8.6

**Comment by tmbo** [comment]
Yes so as stated in the above issue - this is caused by the switch from gevent version 1.2.2 to a 1.3.x version.

**Comment by Walter-Ullon** [comment]
@tmbo Should fixing the version of gevent to 1.2.2 work? I've tried that as well and the build gets hung up without any logs.

**Comment by praveenrengarajan** [comment]
@tmbo what is the solution for this? https://stackoverflow.com/questions/50461657/modulenotfounderror-no-module-named-gevent-wsgi-anaconda 
gvenent version = 1.2.2.
rasa-core = 0.9.0a3
python 3.6
