### ISSUE TITLE
KeyError: 'prefix5' when running rasa_core

### ISSUE THREAD

**Issue by sherinmannambeth** [RasaHQ/rasa_core#632]
**Rasa Core version**:0.9.6

**Python version**: Python 3.6.1 :: Anaconda 4.4.0 (64-bit)

**Operating system** (windows, osx, ...): Windows 8.1

**Issue**:
C:\Users\1807\Desktop\rasa_git\rasa_core\examples\restaurantbot>python -m rasa_core.run -d models/dialogue -u models/nlu/default/model_20180619-044555
2018-06-19 07:28:54 WARNING  py.warnings  - C:\Users\1807\Anaconda3\lib\site-packages\h5py\__init__.py:34
: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is depreca
ted. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

Using TensorFlow backend.
2018-06-19 07:29:16 WARNING  py.warnings  - C:\Users\1807\Anaconda3\lib\site-packages\sklearn\base.py:311
: UserWarning: Trying to unpickle estimator LabelEncoder from version 0.18.1 when using version 0.19.1. T
his might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

2018-06-19 07:29:16 WARNING  py.warnings  - C:\Users\1807\Anaconda3\lib\site-packages\sklearn\base.py:311
: UserWarning: Trying to unpickle estimator SVC from version 0.18.1 when using version 0.19.1. This might
 lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

2018-06-19 07:29:16 WARNING  py.warnings  - C:\Users\1807\Anaconda3\lib\site-packages\sklearn\base.py:311
: UserWarning: Trying to unpickle estimator GridSearchCV from version 0.18.1 when using version 0.19.1. T
his might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

Bot loaded. Type a message and press enter:
hi
Traceback (most recent call last):
  File "C:\Users\1807\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\1807\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\1807\Anaconda3\lib\site-packages\rasa_core\run.py", line 171, in <module>
    cmdline_args.credentials)
  File "C:\Users\1807\Anaconda3\lib\site-packages\rasa_core\run.py", line 153, in main
    agent.handle_channel(input_channel)
  File "C:\Users\1807\Anaconda3\lib\site-packages\rasa_core\agent.py", line 160, in handle_channel
    processor.handle_channel(input_channel)
  File "C:\Users\1807\Anaconda3\lib\site-packages\rasa_core\processor.py", line 61, in handle_channel
    input_channel.start_sync_listening(self.handle_message)
  File "C:\Users\1807\Anaconda3\lib\site-packages\rasa_core\channels\console.py", line 52, in start_sync_
listening
    self._record_messages(message_handler)
  File "C:\Users\1807\Anaconda3\lib\site-packages\rasa_core\channels\console.py", line 45, in _record_mes
sages
    self.sender_id))
  File "C:\Users\1807\Anaconda3\lib\site-packages\rasa_core\processor.py", line 83, in handle_message
    self._handle_message_with_tracker(message, tracker)
  File "C:\Users\1807\Anaconda3\lib\site-packages\rasa_core\processor.py", line 223, in _handle_message_w
ith_tracker
    parse_data = self._parse_message(message)
  File "C:\Users\1807\Anaconda3\lib\site-packages\rasa_core\processor.py", line 212, in _parse_message
    parse_data = self.interpreter.parse(message.text)
  File "C:\Users\1807\Anaconda3\lib\site-packages\rasa_core\interpreter.py", line 232, in parse
    return self.interpreter.parse(text)
  File "C:\Users\1807\Anaconda3\lib\site-packages\rasa_nlu\model.py", line 340, in parse
    component.process(message, **self.context)
  File "C:\Users\1807\Anaconda3\lib\site-packages\rasa_nlu\extractors\crf_entity_extractor.py", line 126,
 in process
    extracted = self.add_extractor_name(self.extract_entities(message))
  File "C:\Users\1807\Anaconda3\lib\site-packages\rasa_nlu\extractors\crf_entity_extractor.py", line 145,
 in extract_entities
    features = self._sentence_to_features(text_data)
  File "C:\Users\1807\Anaconda3\lib\site-packages\rasa_nlu\extractors\crf_entity_extractor.py", line 361,
 in _sentence_to_features
    value = self.function_dict[feature](word)
KeyError: 'prefix5'

**Content of domain file** (if used & relevant):
```
action_factory: null
action_names:
- utter_greet
- utter_goodbye
- utter_default
- utter_ack_dosearch
- utter_ack_findalternatives
- utter_ack_makereservation
- utter_ask_cuisine
- utter_ask_howcanhelp
- utter_ask_location
- utter_ask_moreupdates
- utter_ask_numpeople
- utter_ask_price
- utter_on_it
- action_search_restaurants
- action_suggest
actions:
- utter_greet
- utter_goodbye
- utter_default
- utter_ack_dosearch
- utter_ack_findalternatives
- utter_ack_makereservation
- utter_ask_cuisine
- utter_ask_howcanhelp
- utter_ask_location
- utter_ask_moreupdates
- utter_ask_numpeople
- utter_ask_price
- utter_on_it
- bot.ActionSearchRestaurants
- bot.ActionSuggest
config:
  store_entities_as_slots: true
entities:
- location
- info
- people
- price
- cuisine
intents:
- greet
- affirm
- deny
- inform
- thankyou
- request_info
slots:
  cuisine:
    initial_value: null
    type: rasa_core.slots.TextSlot
  info:
    initial_value: null
    type: rasa_core.slots.TextSlot
  location:
    initial_value: null
    type: rasa_core.slots.TextSlot
  matches:
    initial_value: null
    type: rasa_core.slots.UnfeaturizedSlot
  people:
    initial_value: null
    type: rasa_core.slots.TextSlot
  price:
    initial_value: null
    type: rasa_core.slots.TextSlot
templates:
  utter_ack_dosearch:
  - text: ok let me see what I can find
  utter_ack_findalternatives:
  - text: ok let me see what else there is
  utter_ack_makereservation:
  - buttons:
    - payload: thank you
      title: thank you
    text: ok making a reservation
  utter_ask_cuisine:
  - text: what kind of cuisine would you like?
  utter_ask_howcanhelp:
  - text: how can I help you?
  utter_ask_location:
  - text: where?
  utter_ask_moreupdates:
  - text: if you'd like to modify anything else, please tell me what
  utter_ask_numpeople:
  - text: for how many people?
  utter_ask_price:
  - buttons:
    - payload: cheap
      title: cheap
    - payload: expensive
      title: expensive
    text: in which price range?
  utter_default:
  - text: default message
  utter_goodbye:
  - text: goodbye :(
  - text: Bye-bye
  utter_greet:
  - text: hey there!
  utter_on_it:
  - text: I'm on it
topics: []
```

**Comment by tmbo** [comment]
This looks like you are trying to load a rasa NLU from an older version with a newer version. Retraining the NLU model should fix this issue.

**Comment by sherinmannambeth** [comment]
@tmbo This error comes when I give the rasa_core.run command
This error gets solved when I remove the 'prefix5' from metadata.json file in trained nlu model(which I dont think is the solution)

**Comment by akelad** [comment]
yes, it's an NLU issue though. Have you tried retraining?

**Comment by sherinmannambeth** [comment]
@akelad Yes, but still the same issue persists.

**Comment by xentnex** [comment]
very interesting. I came accross with the same issue.

1. git clone master branch of rasa-nlu
2. pip install -r requirements....
3. train model with the data directory of the cloned rasa-nlu
4. python 3.6

**Comment by akelad** [comment]
@sherinmannambeth @xentnex have you managed to solve this issue in the meantime?

**Comment by ranjan-sumit** [comment]
I am still facing the issue. 

Bot loaded. Type a message and press enter:
Hello
Traceback (most recent call last):
  File "train_online.py", line 50, in <module>
    run_weather_online(nlu_interpreter)
  File "train_online.py", line 42, in run_weather_online
    max_training_samples=300)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\agent.py", line 300, in train_online
    input_channel)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\policies\online_trainer.py", line 76, in run_online_training
    input_channel if input_channel else ConsoleInputChannel())
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\agent.py", line 160, in handle_channel
    processor.handle_channel(input_channel)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\processor.py", line 61, in handle_channel
    input_channel.start_sync_listening(self.handle_message)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\console.py", line 52, in start_sync_listening
    self._record_messages(message_handler)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\channels\console.py", line 45, in _record_messages
    self.sender_id))
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\processor.py", line 83, in handle_message
    self._handle_message_with_tracker(message, tracker)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\processor.py", line 223, in _handle_message_with_tracker
    parse_data = self._parse_message(message)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\processor.py", line 212, in _parse_message
    parse_data = self.interpreter.parse(message.text)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\interpreter.py", line 232, in parse
    return self.interpreter.parse(text)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\model.py", line 340, in parse
    component.process(message, **self.context)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\extractors\crf_entity_extractor.py", line 126, in process
    extracted = self.add_extractor_name(self.extract_entities(message))
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\extractors\crf_entity_extractor.py", line 145, in extract_entities
    features = self._sentence_to_features(text_data)
  File "C:\Users\sumit\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\extractors\crf_entity_extractor.py", line 361, in _sentence_to_features
    value = self.function_dict[feature](word)
KeyError: 'prefix5'

Please help with this
