### ISSUE TITLE
cannot run graphviz python3.6 win10 environment

### ISSUE THREAD

**Issue by e8180kimo** [RasaHQ/rasa_core#783]
**Rasa Core version**: 0.98

**Python version**: 3.6

**Operating system** (windows, osx, ...): win 10

**Issue**:
I followed the [suggestion](https://github.com/ContinuumIO/anaconda-issues/issues/1666) and install it by running `conda install python-graphviz` and the commandline shows install successful.
I also install Graphviz through its website and added the path to my environment.
https://emden.github.io/_pages/Download/Download_windows.html

However, when I run `python -m rasa_core.visualize -d domain.yml -s data/stories.md -o graph.png`
It cannot run by showing:
```
C:\Users\e8180\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Processed Story Blocks: 100%|█████████████████████████████████████████████| 2/2 [00:00<00:00, 501.20it/s, # trackers=1]
Traceback (most recent call last):
  File "C:\Users\e8180\Anaconda3\lib\site-packages\networkx\drawing\nx_agraph.py", line 135, in to_agraph
    import pygraphviz
ModuleNotFoundError: No module named 'pygraphviz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\e8180\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\e8180\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\e8180\Anaconda3\lib\site-packages\rasa_core\visualize.py", line 73, in <module>
    nlu_training_data=nlu_data)
  File "C:\Users\e8180\Anaconda3\lib\site-packages\rasa_core\agent.py", line 356, in visualize
    should_merge_nodes, fontsize)
  File "C:\Users\e8180\Anaconda3\lib\site-packages\rasa_core\training\visualization.py", line 315, in visualize_stories
    persist_graph(G, output_file)
  File "C:\Users\e8180\Anaconda3\lib\site-packages\rasa_core\training\visualization.py", line 220, in persist_graph
    A = nx.nx_agraph.to_agraph(G)  # convert to a graphviz graph
  File "C:\Users\e8180\Anaconda3\lib\site-packages\networkx\drawing\nx_agraph.py", line 138, in to_agraph
    'http://pygraphviz.github.io/')
ImportError: ('requires pygraphviz ', 'http://pygraphviz.github.io/')
```
**Content of domain file** (if used & relevant):
```yaml

```

**Comment by e8180kimo** [comment]
@auzair92 this is not for windows...

**Comment by akelad** [comment]
Have you ran `pip install pygraphviz` ?

**Comment by e8180kimo** [comment]
@akelad Yes, but got errors.
```
Collecting pygraphviz
  Using cached https://files.pythonhosted.org/packages/98/bb/a32e33f7665b921c926209305dde66fe41003a4ad934b10efb7c1211a419/pygraphviz-1.3.1.tar.gz
Building wheels for collected packages: pygraphviz
  Running setup.py bdist_wheel for pygraphviz ... error
  Complete output from command C:\Users\e8180\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\e8180\\AppData\\Local\\Temp\\pip-install-xb4cpd45\\pygraphviz\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\e8180\AppData\Local\Temp\pip-wheel-rdxrvdz2 --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\pygraphviz
  copying pygraphviz\agraph.py -> build\lib.win-amd64-3.6\pygraphviz
  copying pygraphviz\graphviz.py -> build\lib.win-amd64-3.6\pygraphviz
  copying pygraphviz\release.py -> build\lib.win-amd64-3.6\pygraphviz
  copying pygraphviz\version.py -> build\lib.win-amd64-3.6\pygraphviz
  copying pygraphviz\__init__.py -> build\lib.win-amd64-3.6\pygraphviz
  creating build\lib.win-amd64-3.6\pygraphviz\tests
  copying pygraphviz\tests\test.py -> build\lib.win-amd64-3.6\pygraphviz\tests
  copying pygraphviz\tests\test_attributes.py -> build\lib.win-amd64-3.6\pygraphviz\tests
  copying pygraphviz\tests\test_attribute_defaults.py -> build\lib.win-amd64-3.6\pygraphviz\tests
  copying pygraphviz\tests\test_clear.py -> build\lib.win-amd64-3.6\pygraphviz\tests
  copying pygraphviz\tests\test_drawing.py -> build\lib.win-amd64-3.6\pygraphviz\tests
  copying pygraphviz\tests\test_edge_attributes.py -> build\lib.win-amd64-3.6\pygraphviz\tests
  copying pygraphviz\tests\test_graph.py -> build\lib.win-amd64-3.6\pygraphviz\tests
  copying pygraphviz\tests\test_html.py -> build\lib.win-amd64-3.6\pygraphviz\tests
  copying pygraphviz\tests\test_layout.py -> build\lib.win-amd64-3.6\pygraphviz\tests
  copying pygraphviz\tests\test_node_attributes.py -> build\lib.win-amd64-3.6\pygraphviz\tests
  copying pygraphviz\tests\test_readwrite.py -> build\lib.win-amd64-3.6\pygraphviz\tests
  copying pygraphviz\tests\test_string.py -> build\lib.win-amd64-3.6\pygraphviz\tests
  copying pygraphviz\tests\test_subgraph.py -> build\lib.win-amd64-3.6\pygraphviz\tests
  copying pygraphviz\tests\test_unicode.py -> build\lib.win-amd64-3.6\pygraphviz\tests
  copying pygraphviz\tests\__init__.py -> build\lib.win-amd64-3.6\pygraphviz\tests
  running egg_info
  writing pygraphviz.egg-info\PKG-INFO
  writing dependency_links to pygraphviz.egg-info\dependency_links.txt
  writing top-level names to pygraphviz.egg-info\top_level.txt
  reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*~' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '.svn' found anywhere in distribution
  no previously-included directories found matching 'doc\build'
  writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
  copying pygraphviz\graphviz.i -> build\lib.win-amd64-3.6\pygraphviz
  copying pygraphviz\graphviz_wrap.c -> build\lib.win-amd64-3.6\pygraphviz
  running build_ext
  building 'pygraphviz._graphviz' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\pygraphviz
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\e8180\Anaconda3\include -IC:\Users\e8180\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\cppwinrt" /Tcpygraphviz/graphviz_wrap.c /Fobuild\temp.win-amd64-3.6\Release\pygraphviz/graphviz_wrap.obj
  graphviz_wrap.c
  pygraphviz/graphviz_wrap.c(2954): fatal error C1083: Cannot open include file: 'graphviz/cgraph.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for pygraphviz
  Running setup.py clean for pygraphviz
Failed to build pygraphviz
Installing collected packages: pygraphviz
  Running setup.py install for pygraphviz ... error
    Complete output from command C:\Users\e8180\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\e8180\\AppData\\Local\\Temp\\pip-install-xb4cpd45\\pygraphviz\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\e8180\AppData\Local\Temp\pip-record-ufyckntx\install-record.txt --single-version-externally-managed --compile:
    running install
    include_dirs=None
    library_dirs=None
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\agraph.py -> build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\graphviz.py -> build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\release.py -> build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\version.py -> build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\__init__.py -> build\lib.win-amd64-3.6\pygraphviz
    creating build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_attributes.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_attribute_defaults.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_clear.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_drawing.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_edge_attributes.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_graph.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_html.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_layout.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_node_attributes.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_readwrite.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_string.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_subgraph.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_unicode.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\__init__.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    running egg_info
    writing pygraphviz.egg-info\PKG-INFO
    writing dependency_links to pygraphviz.egg-info\dependency_links.txt
    writing top-level names to pygraphviz.egg-info\top_level.txt
    reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.svn' found anywhere in distribution
    no previously-included directories found matching 'doc\build'
    writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
    copying pygraphviz\graphviz.i -> build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\graphviz_wrap.c -> build\lib.win-amd64-3.6\pygraphviz
    running build_ext
    building 'pygraphviz._graphviz' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\pygraphviz
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -INone -IC:\Users\e8180\Anaconda3\include -IC:\Users\e8180\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\cppwinrt" /Tcpygraphviz/graphviz_wrap.c /Fobuild\temp.win-amd64-3.6\Release\pygraphviz/graphviz_wrap.obj
    graphviz_wrap.c
    pygraphviz/graphviz_wrap.c(2954): fatal error C1083: Cannot open include file: 'graphviz/cgraph.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Users\e8180\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\e8180\\AppData\\Local\\Temp\\pip-install-xb4cpd45\\pygraphviz\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\e8180\AppData\Local\Temp\pip-record-ufyckntx\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\e8180\AppData\Local\Temp\pip-install-xb4cpd45\pygraphviz\
```

**Comment by akelad** [comment]
Have you tried installing with something like this? `pip install pygraphviz --install-option="--include-path=C:\Program Files (x86)\Graphviz2.38\include\graphviz" --install-option="--library-path=C:\Program Files (x86)\Graphviz2.38\lib"` 
using the paths wherever your version of Graphviz was installed

**Comment by e8180kimo** [comment]
@akelad Yes, I did, but returns errors
```
$ pip install pygraphviz --install-option="--include-path=C:\Graphviz2.38\include\graphviz" --install-option="--library
-path=C:\Graphviz2.38\lib"
c:\users\e8180\anaconda3\lib\site-packages\pip\_internal\commands\install.py:206: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting pygraphviz
  Using cached https://files.pythonhosted.org/packages/98/bb/a32e33f7665b921c926209305dde66fe41003a4ad934b10efb7c1211a419/pygraphviz-1.3.1.tar.gz
Skipping bdist_wheel for pygraphviz, due to binaries being disabled for it.
Installing collected packages: pygraphviz
  Running setup.py install for pygraphviz ... error
    Complete output from command c:\users\e8180\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\e8180\\AppData\\Local\\Temp\\pip-install-8yb13ph5\\pygraphviz\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\e8180\AppData\Local\Temp\pip-record-47ile7a3\install-record.txt --single-version-externally-managed --compile --include-path=C:\Graphviz2.38\include\graphviz --library-path=C:\Graphviz2.38\lib:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\agraph.py -> build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\graphviz.py -> build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\release.py -> build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\version.py -> build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\__init__.py -> build\lib.win-amd64-3.6\pygraphviz
    creating build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_attributes.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_attribute_defaults.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_clear.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_drawing.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_edge_attributes.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_graph.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_html.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_layout.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_node_attributes.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_readwrite.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_string.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_subgraph.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\test_unicode.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    copying pygraphviz\tests\__init__.py -> build\lib.win-amd64-3.6\pygraphviz\tests
    running egg_info
    writing pygraphviz.egg-info\PKG-INFO
    writing dependency_links to pygraphviz.egg-info\dependency_links.txt
    writing top-level names to pygraphviz.egg-info\top_level.txt
    reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.svn' found anywhere in distribution
    no previously-included directories found matching 'doc\build'
    writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
    copying pygraphviz\graphviz.i -> build\lib.win-amd64-3.6\pygraphviz
    copying pygraphviz\graphviz_wrap.c -> build\lib.win-amd64-3.6\pygraphviz
    running build_ext
    building 'pygraphviz._graphviz' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\pygraphviz
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Graphviz2.38\include\graphviz -Ic:\users\e8180\anaconda3\include -Ic:\users\e8180\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\cppwinrt" /Tcpygraphviz/graphviz_wrap.c /Fobuild\temp.win-amd64-3.6\Release\pygraphviz/graphviz_wrap.obj
    graphviz_wrap.c
    pygraphviz/graphviz_wrap.c(2954): fatal error C1083: Cannot open include file: 'graphviz/cgraph.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\e8180\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\e8180\\AppData\\Local\\Temp\\pip-install-8yb13ph5\\pygraphviz\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\e8180\AppData\Local\Temp\pip-record-47ile7a3\install-record.txt --single-version-externally-managed --compile --include-path=C:\Graphviz2.38\include\graphviz --library-path=C:\Graphviz2.38\lib" failed with error code 1 in C:\Users\e8180\AppData\Local\Temp\pip-install-8yb13ph5\pygraphviz\
```

**Comment by akelad** [comment]
I'm afraid this might be a compatibility issue of pygraphviz with python 3.6 and windows... I'm not sure there's anything we can do about it, I can only suggest googling to see if other people have found a fix to this

**Comment by Aarbor1** [comment]
i'm also facing same problem, Are you find any solution to solve it @e8180kimo

**Comment by Frackup** [comment]
In fact you can go further this issue (I meanby not finding graphviz/cgraph.h), but I then get stuck on another point.

To go beyond this point you got to do as mentionned by Akelad, but removing the \graphviz after the \include

pip install pygraphviz --install-option="--include-path=C:\Program Files (x86)\Graphviz2.38\include" --install-option="--library-path=C:\Program Files (x86)\Graphviz2.38\lib"

Then the issue become (at least for me) : graphviz_wrap.obj : error LNK2001: unresolved external symbol PyIOBase_Type
