### ISSUE TITLE
Custom output and the new name() property/function

### ISSUE THREAD

**Issue by PierrePaul** [RasaHQ/rasa_core#801]
**Rasa Core version**: 0.10.2

**Python version**: 3.5

**Operating system** (windows, osx, ...): linux - ubuntu 18.04

**Issue**: The migration doc to > 0.10.x says we need to implement a new `name()` **property**.
https://github.com/RasaHQ/rasa_core/blob/0.10.2/docs/migrations.rst
The dispatcher though, calls a `name()` **function**.
https://github.com/RasaHQ/rasa_core/blob/0.10.2/rasa_core/dispatcher.py#L172

Also important, doc mention the CollectingOutputChannel as a template to use. It uses a **property**.
https://github.com/RasaHQ/rasa_core/blob/0.10.2/rasa_core/channels/direct.py#L10

And the full error with python3.5 when using a property : 
```
ERROR:rasa_core.processor:'str' object is not callable                                                                                       │                                                                                                                                            
Traceback (most recent call last):                                                                                                           │                                                                                                                                            
  File "<redacted>/lib/python3.5/site-packages/rasa_core/processor.py", line 311, in _run_action               │                                                                                                                                            
    events = action.run(dispatcher, tracker, self.domain)                                                                                    │                                                                                                                                            
  File "<redacted>/lib/python3.5/site-packages/rasa_core/actions/action.py", line 72, in run                   │                                                                                                                                            
    tracker)                                                                                                                                 │                                                                                                                                            
  File "<redacted>/lib/python3.5/site-packages/rasa_core/dispatcher.py", line 154, in utter_template           │                                                                                                                                            
    **kwargs)                                                                                                                                │                                                                                                                                            
  File "<redacted>/lib/python3.5/site-packages/rasa_core/dispatcher.py", line 172, in _generate_response       │                                                                                                                                            
    self.output_channel.name(),                                                                                                              │                                                                                                                                            
TypeError: 'str' object is not callable 
```

**Comment by akelad** [comment]
Is this happening with a custom channel you've created or with the inbuilt ones? could you also post the relevant domain file? and the full error trace please :)

**Comment by PierrePaul** [comment]
It's a custom channel we have made.
```
DEBUG:rasa_core.policies.memoization:Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
DEBUG:rasa_core.policies.memoization:There is a memorised next action '3' 
DEBUG:rasa_core.policies.ensemble:Predicted next action using policy_0_MemoizationPolicy
DEBUG:rasa_core.policies.ensemble:Predicted next action 'utter_greet' with prob 1.00.
ERROR:rasa_core.processor:Encountered an exception while running action 'utter_greet'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
ERROR:rasa_core.processor:'str' object is not callable
Traceback (most recent call last):
  File "<redacted>/.virtualenvs/<redacted>/lib/python3.5/site-packages/rasa_core/processor.py", line 311, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "<redacted>/.virtualenvs/<redacted>/lib/python3.5/site-packages/rasa_core/actions/action.py", line 72, in run 
    tracker)
  File "<redacted>/.virtualenvs/<redacted>/lib/python3.5/site-packages/rasa_core/dispatcher.py", line 154, in utter_template
    **kwargs)
  File "<redacted>/.virtualenvs/<redacted>/lib/python3.5/site-packages/rasa_core/dispatcher.py", line 172, in _generate_response
    self.output_channel.name(),
TypeError: 'str' object is not callable
DEBUG:rasa_core.processor:Action 'utter_greet' ended with events '[]'
DEBUG:rasa_core.policies.memoization:Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}]
DEBUG:rasa_core.policies.memoization:There is a memorised next action '0' 
DEBUG:rasa_core.policies.ensemble:Predicted next action using policy_0_MemoizationPolicy
DEBUG:rasa_core.policies.ensemble:Predicted next action 'action_listen' with prob 1.00.
DEBUG:rasa_core.processor:Action 'action_listen' ended with events '[]'
```

I can't post the domain file, but I will try to replicate with an empty one.

**Comment by PierrePaul** [comment]
Yeah, so it also happens with the domain file from the tutorial : 
```
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey! How are you?"
    buttons:
    - title: "great"
      payload: "great"
    - title: "super sad"
      payload: "super sad"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"
```

**Comment by PierrePaul** [comment]
Also, Im not sure if I was clear enough, but changing
```python
    @property
    def name(cls):
        return "myoutputchannel"
```
To
```python
    def name(self):
        return "myoutputchannel
```
Fixes the issue.

**Comment by akelad** [comment]
@tmbo can you look into this?

**Comment by tmbo** [comment]
Yes @PierrePaul, we should have been clearer in the documentation about this: it should be a method as you said and not a property.

**Comment by tmbo** [comment]
wait, I just checked the migrations doc and it never says that you should use `@property`, but rather `@classname`. now I am confused and not quite sure what you mean, because `@classname` is correct.

**Comment by PierrePaul** [comment]
I... have no idea what happened. Even the git history shows no sign of `@property`. I'm so sorry!

**Comment by tmbo** [comment]
No worries 😃
