### ISSUE TITLE
Missing section on how to contribute and pytest error

### ISSUE THREAD

**Issue by benjamin-work** [RasaHQ/rasa_core#84]
**Rasa Core version**
`0.7.3`

**Operating system**
Ubuntu 16.04

**Issue**:

Currently, I can't find any section on how to contribute. The link in the README is pointing nowhere.

I actually had problems making the tests run, presumably I'm missing something. The error is:

```
$ py.test
Traceback (most recent call last):
  File "/home/bbossan_dev/anaconda3/lib/python3.5/site-packages/_pytest/config.py", line 283, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/mnt/data01/work/ben/forks/rasa_core/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/bbossan_dev/anaconda3/lib/python3.5/site-packages/_pytest/config.py", line 314, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/mnt/data01/work/ben/forks/rasa_core/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/bbossan_dev/anaconda3/lib/python3.5/site-packages/_pytest/config.py", line 320, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/bbossan_dev/anaconda3/lib/python3.5/site-packages/py/_path/local.py", line 650, in pyimport
    __import__(modname)
  File "/mnt/data01/work/ben/forks/rasa_core/tests/conftest.py", line 11, in <module>
    from rasa_core.agent import Agent
  File "/mnt/data01/work/ben/forks/rasa_core/rasa_core/agent.py", line 12, in <module>
    from rasa_core.domain import TemplateDomain, Domain
  File "/mnt/data01/work/ben/forks/rasa_core/rasa_core/domain.py", line 16, in <module>
    from pykwalify.errors import SchemaError
ImportError: No module named 'pykwalify'
ERROR: could not load /mnt/data01/work/ben/forks/rasa_core/tests/conftest.py
```

However, `pykwalify` is installed:

```
$ pip list | grep pykwalify
pykwalify (1.6.0)
```

**Comment by tmbo** [comment]
`py.test` in your above log is using python 3. depending on your setup, `pip list` usually shows packages installed for python 2.7. so might be that the package is not installed for python 3.

**Comment by tmbo** [comment]
You can also use the makefile commands to run the tests. But I agree - there should be a section about contributions.

**Comment by benjamin-work** [comment]
I use a conda environment, and `pykwalify` is part of that environment. Running `make test` results in the same error.

**Comment by tmbo** [comment]
Did you run `pip install -r dev-requirements.txt`?

**Comment by benjamin-work** [comment]
Yes:

```
conda create -n rasa_core2 python=2.7
source activate rasa_core2
pip install -r requirements.txt 
pip install -r dev-requirements.txt 
python setup.py develop
py.test
```

The same with Python 3.6.

Interestingly, `pykwalify` seems to be installed:

```
$ python -c 'from pykwalify.errors import SchemaError;print("works")'
works
```

My colleague reprocuded the problem on his machine.

**Comment by tmbo** [comment]
ok let me try that sequence as well

**Comment by benjamin-work** [comment]
Okay, I discovered the source of the problem: pytest itself is missing from the requirements. Therefore, invoking the tests resulted in invoking the global pytest.

**Comment by tmbo** [comment]
I've added `pytest` to the dependencies, so this should be fixed.
