### ISSUE TITLE
Display buttons using rest api

### ISSUE THREAD

**Issue by chinnusujitha** [RasaHQ/rasa_core#859]
**Rasa Core version**: 0.8.3

**Python version**: python 3.6.3

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:
I wrote a rest api which is defined in #119 
Now i want to display buttons that are defined in my yaml file using rest api, (OR) is there any way to return the response through rest api in this format:
{
type : "text",
message : "how can i help you"
}
{
type : "buttons",
message : "we are providing options for : ",
options : ["option1", "option2" ]
}

**Content of domain file** (if used & relevant):
```utter_greet:

text: "Hey! How are you?"
buttons:
title: "great"
payload: "great"
title: "super sad"
payload: "super sad

```

**Comment by akelad** [comment]
Thanks for creating this issue, @ricwo will get back to you about it soon.

**Comment by ricwo** [comment]
Hey! Since you're using the `CollectingOutputChannel`, button messages will be of the form `{"recipient_id": recipient_id, "text": message, "data": buttons}`, so you could something like

```python
(...)
out = CollectingOutputChannel()
on_new_message(UserMessage(text, out, sender_id))
out_list = []
for m in out.messages:
    message_dict = {
        "message": out.get("text")
    }
    if out.get("data") is not None:  # button message
        options = [b.title for b in out["data"]]
        message_dict["type"] = "buttons"
        message_dict["options"] = options
    else:  # text message
        message_dict["type"] = "text"
    out_list.append(message_dict)
return jsonify(out_list)
```

This is assuming you want the `Button`'s `title` and not `payload` in your options list (call `b.payload` to get the payload).
Let me know if that helps!

**Comment by chinnusujitha** [comment]
I'm getting this error:

> [2018-08-14 16:16:04,107] ERROR in app: Exception on /chat/ [POST]
Traceback (most recent call last):
 File "/home/.local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/.local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/.local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/.local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
   raise value
 File "/home/.local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/.local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "serve.py", line 49, in receive
   "message": out.get("text")
AttributeError: 'CollectingOutputChannel' object has no attribute 'get'

**Comment by ricwo** [comment]
Apologies, the loop should be
```
for m in out.messages:
    message_dict = {
        "message": out.text
    }
    if out.data:  # button message
        options = [b.title for b in out.data]
        message_dict["type"] = "buttons"
        message_dict["options"] = options
    else:  # text message
        message_dict["type"] = "text"
    out_list.append(message_dict)
```

Could you confirm if that works?

**Comment by chinnusujitha** [comment]
@ricwo can you please look into this

**Comment by ricwo** [comment]
@chinnusujitha I see you're using `0.8.3`, where the messages appended in the channel you're using were a different format. `CollectingOutputChannel` in `0.8.3` doesn't support button message out of the box. Would you be able to upgrade to the latest version of rasa core? in that case the snippet I posted should work

**Comment by chinnusujitha** [comment]
Hi i changed the loop to this and it worked for me. Thank you very much @ricwo for helping me on this.

     for m in out.messages:
               message_dict = {
                   "message": m.get("text")
               }
               if m.get("data"):  # button message
                   options = [b.get("title") for b in m.get("data")]
                   message_dict["type"] = "buttons"
                   message_dict["options"] = options
                       out_list.append(message_dict)
               else:  # text message
                   message_dict["type"] = "text"
               out_list.append(message_dict)

**Comment by chinnusujitha** [comment]
Is there is any way to return the text intent also??

**Comment by chinnusujitha** [comment]
@ricwo @akelad is there is any way to return the text intent also or which utter query(action) has executed??

**Comment by chinnusujitha** [comment]
Can't we do that in my domain.yml file itself ? Because i have too many intents and i think writing actions for simple intents will effect in my code optimization.

**Comment by akelad** [comment]
If you run Rasa Core in [debug mode](http://rasa.com/docs/core/debugging/), the recognised intent and predicted actions will get printed to the logger

**Comment by chinnusujitha** [comment]
Not to the logger, i need to return intent also in my rest api  response.

**Comment by ricwo** [comment]
If you don't want to have custom actions for every UtterAction, you could modify the `UtterAction` class. Its run method could look something like this
```python
def run(self, dispatcher, tracker, domain):
    import json
    
    template_message = dispatcher.retrieve_template(
            self.name(),
            filled_slots=tracker.current_slot_values()
    )
    
    latest_intent = tracker.latest_message.intent.get("name")
    
    utter_dict = {"text": template_message,
                  "intent": latest_intent,
                  "action": self.name()}

    dispatcher.utter_message(json.dumps(utter_dict))

    return []
```
