### ISSUE TITLE
ruamel.yaml.scanner.ScannerError: mapping values are not allowed in this context   in "<unicode string>", line 2, column 8

### ISSUE THREAD

**Issue by loveJasmine** [RasaHQ/rasa_core#898]
(.venv) mldl@ub1604:/ub16_prj/rasa_core$ python3 -m rasa_core.train -d domain.yml -s stories.md -o models/dialogue
/home/mldl/ub16_prj/rasa_core/.venv/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mldl/ub16_prj/rasa_core/rasa_core/train.py", line 191, in <module>
    additional_arguments)
  File "/home/mldl/ub16_prj/rasa_core/rasa_core/train.py", line 152, in train_dialogue_model
    policies=policies)
  File "/home/mldl/ub16_prj/rasa_core/rasa_core/agent.py", line 200, in __init__
    self.domain = self._create_domain(domain)
  File "/home/mldl/ub16_prj/rasa_core/rasa_core/agent.py", line 618, in _create_domain
    return Domain.load(domain)
  File "/home/mldl/ub16_prj/rasa_core/rasa_core/domain.py", line 89, in load
    return cls.from_yaml(read_file(filename))
  File "/home/mldl/ub16_prj/rasa_core/rasa_core/domain.py", line 93, in from_yaml
    cls.validate_domain_yaml(yaml)
  File "/home/mldl/ub16_prj/rasa_core/rasa_core/domain.py", line 123, in validate_domain_yaml
    source_data = utils.read_yaml_string(yaml)
  File "/home/mldl/ub16_prj/rasa_core/rasa_core/utils.py", line 338, in read_yaml_string
    return yaml_parser.load(string)
  File "/home/mldl/ub16_prj/rasa_core/.venv/lib/python3.5/site-packages/ruamel/yaml/main.py", line 266, in load
    return constructor.get_single_data()
  File "/home/mldl/ub16_prj/rasa_core/.venv/lib/python3.5/site-packages/ruamel/yaml/constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 725, in _ruamel_yaml.CParser._compose_document
  File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event
ruamel.yaml.scanner.ScannerError: mapping values are not allowed in this context
  in "<unicode string>", line 2, column 8
(.venv) mldl@ub1604:~/ub16_prj/rasa_core$

**Comment by akelad** [comment]
Please fill out the template when creating an issue

 

**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:



**Content of domain file** (if used & relevant):
```yaml

```

**Comment by loveJasmine** [comment]
Rasa Core version:
latest
Python version:
python3.5
Operating system (windows, osx, ...):
ubuntu16
Issue:
----list above
Content of domain file (if used & relevant):


story file:
## happy path
* greet
  - utter_greet
* mood_great
  - utter_happy

## sad path 1
* greet
  - utter_greet
* mood_unhappy
  - utter_cheer_up
  - utter_did_that_help
* mood_affirm
  - utter_happy

## sad path 2
* greet
  - utter_greet
* mood_unhappy
  - utter_cheer_up
  - utter_did_that_help
* mood_deny
  - utter_goodbye

## say goodbye
* goodbye
  - utter_goodbye



domain file:
domain_yml = """
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"
"""
