### ISSUE TITLE
json or yml format for config rasa training

### ISSUE THREAD

**Issue by e8180kimo** [RasaHQ/rasa_core#908]
**Rasa Core version**: 0.10.4

**Python version**: 3.7

**Operating system** (windows, osx, ...): osx

**Issue**:
I am following a tutorial to build my rasa bot on my local webserver
[tutorial](https://www.analyticsvidhya.com/blog/2018/01/faq-chatbots-the-future-of-information-searching/)

This tutorial is using `json` format for the `config` file. However, my config is `yml` format.
To build rasa onto a web server, do I have to use the json format? 
--if so, is there an easy way to convert my yml to json?

Does rasa_nlu.server only support json?

This is my config.yml:
```
language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "ner_crf"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
```

**Comment by amn41** [comment]
As of 0.12 we separated out model configuration from server configuration, and model config is always in yaml (as you have it here). See the [changelog](https://github.com/RasaHQ/rasa_nlu/blob/master/CHANGELOG.rst#0120---2018-04-17)

you can pass arguments to the server (like what port to listen on) via command line arguments, see [here](https://rasa.com/docs/nlu/config/)

**Comment by e8180kimo** [comment]
@amn41 I've trained rasa nlu. But there is no `project` in my folder
My trained mode folder is like this:
```
--Models
----nlu
------default
--------current
----current
------dialogue
```
But when I run the server using `python -m rasa_nlu.server -c config_spacy.yml --path /models` and `curl -XPOST localhost:5000/parse -d '{"q":"motivation"}'` , it returns: 
```
{
  "intent": {
    "name": null,
    "confidence": 1.0
  },
  "entities": [],
  "text": "motivation",
  "project": "default",
  "model": "fallback"
```
This is incorrect though.

**Comment by amn41** [comment]
try with `python -m rasa_nlu.server -c config_spacy.yml --path ./Models/nlu` and then 

`curl -XPOST localhost:5000/parse?model=current -d '{"q":"motivation"}'`

**Comment by e8180kimo** [comment]
@amn41 it returns
{
  "error": "Unable to initialize persistor"
}

**Comment by venky14** [comment]
Same here

Error: 
```
```

**Comment by venky14** [comment]
same error here

```
2018-09-11 11:36:49+0530 [-] 2018-09-11 11:36:49 WARNING  rasa_nlu.project  - Using default interpreter, couldn't fetch model: Unable to initialize persistor
2018-09-11 11:36:49+0530 [-] 2018-09-11 11:36:49 ERROR    __main__  - Unable to initialize persistor
```

In detail

```
Aech:~ priya$ python -m rasa_nlu.server -c ./r_nlu_tf/config.yml --path ./r_nlu_tf/models/nlu
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
/Users/priya/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/Users/priya/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-09-11 11:35:14+0530 [-] Log opened.
2018-09-11 11:35:14+0530 [-] Site starting on 5000
2018-09-11 11:35:14+0530 [-] Starting factory <twisted.web.server.Site object at 0x18152136d8>
2018-09-11 11:36:49+0530 [-] 2018-09-11 11:36:49 WARNING  rasa_nlu.project  - Using default interpreter, couldn't fetch model: Unable to initialize persistor
2018-09-11 11:36:49+0530 [-] 2018-09-11 11:36:49 ERROR    __main__  - Unable to initialize persistor
2018-09-11 11:36:49+0530 [-] Traceback (most recent call last):
2018-09-11 11:36:49+0530 [-]   File "/Users/priya/anaconda3/lib/python3.6/site-packages/rasa_nlu/server.py", line 238, in parse
2018-09-11 11:36:49+0530 [-]     self.data_router.parse, data))
2018-09-11 11:36:49+0530 [-]   File "/Users/priya/anaconda3/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
2018-09-11 11:36:49+0530 [-]     result = inContext.theWork()
2018-09-11 11:36:49+0530 [-]   File "/Users/priya/anaconda3/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
2018-09-11 11:36:49+0530 [-]     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
2018-09-11 11:36:49+0530 [-]   File "/Users/priya/anaconda3/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
2018-09-11 11:36:49+0530 [-]     return self.currentContext().callWithContext(ctx, func, *args, **kw)
2018-09-11 11:36:49+0530 [-]   File "/Users/priya/anaconda3/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
2018-09-11 11:36:49+0530 [-]     return func(*args,**kw)
2018-09-11 11:36:49+0530 [-]   File "/Users/priya/anaconda3/lib/python3.6/site-packages/rasa_nlu/data_router.py", line 242, in parse
2018-09-11 11:36:49+0530 [-]     model)
2018-09-11 11:36:49+0530 [-]   File "/Users/priya/anaconda3/lib/python3.6/site-packages/rasa_nlu/project.py", line 119, in parse
2018-09-11 11:36:49+0530 [-]     interpreter = self._interpreter_for_model(model_name)
2018-09-11 11:36:49+0530 [-]   File "/Users/priya/anaconda3/lib/python3.6/site-packages/rasa_nlu/project.py", line 197, in _interpreter_for_model
2018-09-11 11:36:49+0530 [-]     metadata = self._read_model_metadata(model_name)
2018-09-11 11:36:49+0530 [-]   File "/Users/priya/anaconda3/lib/python3.6/site-packages/rasa_nlu/project.py", line 212, in _read_model_metadata
2018-09-11 11:36:49+0530 [-]     self._load_model_from_cloud(model_name, path)
2018-09-11 11:36:49+0530 [-]   File "/Users/priya/anaconda3/lib/python3.6/site-packages/rasa_nlu/project.py", line 251, in _load_model_from_cloud
2018-09-11 11:36:49+0530 [-]     raise RuntimeError("Unable to initialize persistor")
2018-09-11 11:36:49+0530 [-] RuntimeError: Unable to initialize persistor
2018-09-11 11:36:49+0530 [-] "127.0.0.1" - - [11/Sep/2018:06:06:49 +0000] "POST /parse?model=current HTTP/1.1" 500 47 "-" "curl/7.58.0"
```

**Comment by akelad** [comment]
@amn41 can you please look into what's going wrong there?

**Comment by amn41** [comment]
@venky14  does it work if you specify the project explicitly?

`curl -XPOST 'localhost:5000/parse?model=current&project=nlu' -d '{"q":"motivation"}'`

**Comment by venky14** [comment]
Got this 
```
Aech:~ priya$ curl -XPOST 'localhost:5000/parse?model=current&project=nlu' -d '{"q":"motivation"}'
{
  "error": "Unable to initialize persistor"
}
```

same as above error.
