### ISSUE TITLE
ImportError: ('requires pygraphviz ', 'http://pygraphviz.github.io/')

### ISSUE THREAD

**Issue by Aarbor1** [RasaHQ/rasa_core#995]
**Rasa Core version**:0.11.3

**Python version**: 3.6.4

**Operating system** (windows, osx, ...):Windows 10 64xbit OS

**Issue**:I'm already installed pygraphviz1.5 but when i try to run sample rasa_core concert-bot visualize.py file I'm facing following error

C:\Users\Aarbor 01\rasa_core\examples\concertbot>python visualize.py
C:\ProgramData\Anaconda3\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning:
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
Processed Story Blocks: 100%|███████| 7/7 [00:00<00:00, 7265.56it/s, # trackers=1]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\networkx\drawing\nx_agraph.py", line 132, in to_agraph
    import pygraphviz
  File "C:\Users\Aarbor 01\AppData\Roaming\Python\Python36\site-packages\pygraphviz\__init__.py", line 58, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "C:\Users\Aarbor 01\AppData\Roaming\Python\Python36\site-packages\pygraphviz\agraph.py", line 22, in <module>
    from . import graphviz as gv
  File "C:\Users\Aarbor 01\AppData\Roaming\Python\Python36\site-packages\pygraphviz\graphviz.py", line 28, in <module>
    _graphviz = swig_import_helper()
  File "C:\Users\Aarbor 01\AppData\Roaming\Python\Python36\site-packages\pygraphviz\graphviz.py", line 24, in swig_import_helper
    _mod = imp.load_module('_graphviz', fp, pathname, description)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "visualize.py", line 15, in <module>
    output_file="graph.png", max_history=2)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rasa_core\agent.py", line 602, in visualize
    should_merge_nodes, fontsize)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rasa_core\training\visualization.py", line 323, in visualize_stories
    persist_graph(graph, output_file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rasa_core\training\visualization.py", line 228, in persist_graph
    expg = nx.nx_agraph.to_agraph(graph)  # convert to a graphviz graph
  File "C:\ProgramData\Anaconda3\lib\site-packages\networkx\drawing\nx_agraph.py", line 135, in to_agraph
    'http://pygraphviz.github.io/')
ImportError: ('requires pygraphviz ', 'http://pygraphviz.github.io/')

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
What was the command you ran to install pygraphviz?

**Comment by Aarbor1** [comment]
python setup.py install --user --include-path="C:\Program Files\graphviz-2.38\include" --library-path="C:\Program Files\graphviz-2.38\lib"  @akelad

**Comment by akelad** [comment]
what `setup.py` is this?

**Comment by Aarbor1** [comment]
its pygraphviz-1.5 set.py file

**Comment by akelad** [comment]
can you try importing pygraphviz from the python command line?

**Comment by Frackup** [comment]
Hi, I have the same issue.

Akelad, do you ask to use "`pip install pygraphviz`"? If it's the case, then it's not working on windows and that's why Aarbor1 used this way to install pygraphviz.

But even if it's not with pip, when using "`pip show pygraphviz`", we correctly see that pygraphviz 1.5 is installed, but we're facing the issue mentionned above when trying to use the interactive learning command (or anything asking for visualisation).

**Comment by satishAarbor** [comment]
then what is the solution for it.

**Comment by akelad** [comment]
There's a lot of problems with pygraphviz in Windows, in fact for some versions of Windows it's entirely incompatible. I'm not sure there is a solution to this, perhaps someone has found a solution on Stackoverflow before...
Though, what error are you getting for the interactive learning command? That shouldn't require that.

**Comment by Frackup** [comment]
Hi,

Sorry for the delay, here is the error I got when lauching the interactive learning

```
Traceback (most recent call last):
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\site-packages\networkx\drawing\nx_agraph.py", line 133, in to_agraph
    import pygraphviz
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\site-packages\pygraphviz\__init__.py", line 58, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\site-packages\pygraphviz\agraph.py", line 22, in <module>
    from . import graphviz as gv
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\site-packages\pygraphviz\graphviz.py", line 28, in <module>
    _graphviz = swig_import_helper()
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\site-packages\pygraphviz\graphviz.py", line 24, in swig_import_helper
    _mod = imp.load_module('_graphviz', fp, pathname, description)
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: %1 n’est pas une application Win32 valide.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\train.py", line 239, in <module>
    additional_arguments)
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\train.py", line 185, in train_dialogue_model
    training_data = agent.load_data(stories_file, **data_load_args)
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\agent.py", line 472, in load_data
    debug_plots)
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\training\__init__.py", line 56, in load_data
    debug_plots)
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\training\generator.py", line 168, in __init__
    self.story_graph.visualize('story_blocks_connections.pdf')
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\training\structures.py", line 546, in visualize
    visualization.persist_graph(graph, output_file)
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\training\visualization.py", line 228, in persist_graph
    expg = nx.nx_agraph.to_agraph(graph)  # convert to a graphviz graph
  File "C:\Users\a.vescera\AppData\Local\Programs\Python\Python36\lib\site-packages\networkx\drawing\nx_agraph.py", line 136, in to_agraph
    'http://pygraphviz.github.io/')
ImportError: ('requires pygraphviz ', 'http://pygraphviz.github.io/')
```
